### ISSUE TITLE
unable to select out of bounds dates programmatically

### ISSUE THREAD

**Issue by sandeep251986** [patchthecode/JTAppleCalendar#1028]
Hi, Thanks a lot for providing this library.
Currently i am using latest version 7.1.6.

Currently, i am rendering calendar from 2019-01-01 to 2019-04-30 and rendering out dates **till end of the grid** . i am trying to select entire week of the selected(user initiated) date programmatically. This is working fine if dates are between calendar start date and end date, but it is not working if dates are out of start and end dates.
Currently i am not able to select out dates programmatically but able to select by user initiate
<img width="575" alt="Screenshot 2019-04-03 at 20 49 12" src="https://user-images.githubusercontent.com/33122628/55490787-f9839280-5651-11e9-934b-541aa4597e2e.png">
<img width="572" alt="Screenshot 2019-04-03 at 20 48 14" src="https://user-images.githubusercontent.com/33122628/55490788-fa1c2900-5651-11e9-9d43-f6bceae4f793.png">

**Comment by patchthecode** [comment]
Two things

1. It cannot be done programatically, because it is outside of the date boundary.
2. Now i also had the chance to make the library restrict it for user selection, but i chose not to do it because it would seem weird that the library is restricting it. Because there may be some cases where the programmer maybe want to allow some tapping to do whatever. 
Therefore i left it up the the programmer to stop it. If you want to stop a user from tapping these dates, then set this restriction up in the `shouldSelect` function

**Comment by sandeep251986** [comment]
Thanks for your reply
one thing we can do in this scenario is we can keep calendar start date as 30-12-2018 (i.e start date of the week). so that we can select entire week.
Above solution is working perfectly fine for selecting entire week, but i am facing small issue with this solution i.e after adding 30-12-2018 as calendar start date, now calendar is showing Dec 2018 month dates also. but i don't want to display Dec 2018 dates.

How to restrict scrolling to Dec 2018 month?
is there any other to achieve this requirement?

**Comment by sandeep251986** [comment]
I have found one more issue on selecting entire week, i don't know why 24th Feb 2019 date is not getting selected when trying to select though programmatically, but for remaining days it is working fine.
24th Feb 2019 is inside date boundaries only.
why this issue is occurring for this particular date?
i have attached [image](https://user-images.githubusercontent.com/33122628/55547602-436e8600-56ef-11e9-905a-ec76cf891015.png) and [source code](https://github.com/patchthecode/JTAppleCalendar/files/3042927/CalendarTest.zip)

**Comment by patchthecode** [comment]
Implementing a date boundary can help -> https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by patchthecode** [comment]
Concerning the error you are seeing that feb 34 is selected, I think that you might be seeing a bug that was fixed, but not yet released in version 7.1.8

Can you follow the instructions here to see if this bug is occurring on the master branch? --> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there

**Comment by sandeep251986** [comment]
1. After following your suggested instructions, Feb 24 issue is not occurring now. Issue got resolved
2.  Regarding date boundaries scrolling, achieved required functionality by following your instructions 

Thank you very much for your help.

**Comment by patchthecode** [comment]
awesome. closing this.
