### ISSUE TITLE
Range Selection Dates 

### ISSUE THREAD

**Issue by mohamedfarid1993** [patchthecode/JTAppleCalendar#1053]
Range Selection works perfectly on Calendar but when printing the dates it gives a one day earlier range like when choose 1-1-2018 it gives a date of 31-12-2017 
I don't know what could have went wrong there it could be something went wrong with my implementation but I even tried in the example code and the same happened

**Comment by patchthecode** [comment]
You will see this issue with dates in Swift even if you do not use a calendar library.
For a full explanation on the issue and how to resolve it, see https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
closing this issue. If it is not resolved for you then let me know.

**Comment by patchthecode** [comment]
Summary -> in iOS, you cant just simply print a date to the console. You have to format the date and then print it. 
And why? Because the print() function has its own default date formatting. This formatting might be different to your current region (especially if you live in the east). Therefore, the raw, unformatted, print statement will show a day -1 than the actual day.
Will close this issue, but let me know if still stuck.

**Comment by mohamedfarid1993** [comment]
Thanks a lot for replying this fast and it did solve it

**Comment by patchthecode** [comment]
awesome.
