### ISSUE TITLE
Calendar custom rows offsets months

### ISSUE THREAD

**Issue by bryancaragay** [patchthecode/JTAppleCalendar#1057]
**Version**
7.1.7

**Issue**
Using a custom `ConfigurationParameters` with `numberOfRows = 5`, the calendar gets more and more offset as I scroll through the months.

Eventually I get to a month with the "out dates" in the middle of the page.

**Images**
#### Correct (Start) state
<details>
  <img src="https://user-images.githubusercontent.com/17282887/58487429-2bcedf00-812d-11e9-8ea3-37abe79a0f2c.png" width="375"/>
</details>

#### Weird State
<details>
  <img src="https://user-images.githubusercontent.com/17282887/58487430-2c677580-812d-11e9-8b6f-b1e52d9534f1.png" width="375"/>
</details>

**Expected Behavior**
I would expect the date offsets to maintain the correct placement, with any in dates being at the start, and out dates being at the end, never in the middle.

**Steps to reproduce**
1. Create calendar by following tutorial
2. Use following `ConfigurationParameters`
```
return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 5, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid)
```

**Comment by patchthecode** [comment]
i'll look at this in a bit.
But can you tell me what your scrolling mode is?
If you dont know what this is, or have never set one, then chances are that you are on the default which is `.StopAtEachFrame`

Can you instead set it to `.stopAtEachSection` ?

In your viewDidLoad, put this
```swift
calendarView.scrollingMode = .stopAtEachSection
```

If this resolves the issue, then let me know

**Comment by bryancaragay** [comment]
That seems to have fixed it 👍 I'm not sure if that should go anywhere for people in the future to reference (besides this issue), but it worked.

**Comment by patchthecode** [comment]
@bryancaragay 
ok if this fixed it then what happened was this:

You have a vertical calendar with the scroll mode set to .StopAtEachFrame.
This means it will stop a fixed 300 points (assuming your calendarView is 300 high) on each scroll.

Because you months have a varying number of sizes (not all month have the same size), scrolling with this fixed mode will offset your screen badly. So in a case like yoursm you just want to scroll to each section.  BTW, i am currently re-writing the scroll to section code to make the scrolling feel more "snappy".

**Comment by patchthecode** [comment]
closing this issue.
