### ISSUE TITLE
Start calendar on Monday and not on the 01

### ISSUE THREAD

**Issue by lucojs** [patchthecode/JTAppleCalendar#1063]
I'm using JTAppleCalendar (7.1.7) on branch master

First and foremost, thanks for making this library.

I'm using a vertical scroll calendar and I am unable to change my starting date in the current month, every month is always starting on the 1. Is it possible to change this to make every month starting on Monday by example ?

``` swift
   func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {

        let startDate = Date()
        let endDate = Settings.Date.calendar.date(
            byAdding: .month,
            value: 1,
            to: viewModel.calendarDates.availableDates.last ?? Date())
        calendar.selectDates([viewModel.calendarDates.currentDate])

        return ConfigurationParameters(
            startDate: startDate,
            endDate: endDate ?? Date(),
            numberOfRows: 5,
            calendar: Settings.Date.calendar,
            generateInDates: .forAllMonths,
            generateOutDates: .off,
            firstDayOfWeek: .monday,
            hasStrictBoundaries: false)
    }
```

![Capture d’écran 2019-06-12 à 18 06 11](https://user-images.githubusercontent.com/27230634/59370094-1919f400-8d42-11e9-859d-9ff6ed76a557.png)

**Comment by patchthecode** [comment]
It is not possible to do this.
The variable is called startDate, but it should be called start of month.
I have just never changed it because thats the variable name used since this calendar was created.

But many people have asked for this upgrade already. So i have it as an enhancement to implement once i have the free time -> https://github.com/patchthecode/JTAppleCalendar/issues/716

Maybe in the mean time you can try the boundary dates solution? https://github.com/patchthecode/JTAppleCalendar/issues/365
This solution causes the calendar to become non-scrollable after a certaion specified date.
let me know.

**Comment by patchthecode** [comment]
closing issue
