### ISSUE TITLE
A big overhaul but no love for week view

### ISSUE THREAD

**Issue by pauloec** [patchthecode/JTAppleCalendar#1090]
**(Required) Version Number:** 8.0

## Description
I'm having some issues when trying to use 1 row as to:
Change month name (The only way i see of implementing month header is by using viewForHeader which is something i don't wanna do)
Disable scrolling for dates before startDate

Also, i'm rolling back to 7.1.7. After updating cocoapods and changing the names in all delegates and functions, tapping simply stopped to work. Noticed some other glitches as well so, i'm not sure if this is a known issue or whatnot but this update is proving to be a bothersome instead of an improvement, at least for now.

Love your lib and all the effort you put on it, hope to see more from it. :)

**Comment by patchthecode** [comment]
Thanks.

1. ok. Im am unclear what you mean by `Change month name`.
Can you show me a screen shot of what your calendar looks like so i can have an idea of how to respond?

2. Also, i'm rolling back to 7.1.7. After updating cocoapods and changing the names in all delegates and functions, tapping simply stopped to work. -- This is mentioned on the [migration guide](https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/).

There is an important note in there -->
```
Important: Because the names of some function have changed, if you forget to change their names you might notice things like “my functions are not being called”. If you are experiencing this, changes are you did not change the names.
```

So if your click isnt working, its because you didnt change the function name. Check out the link and see the new function name for didSelect now includes `IndexPath` in the function name.

3.  Noticed some other glitches as well - Let me know what they are.
I made a huge overhaul to include YearView. There were also many issues fixed from version 7.1.7.  If you see any new issues, then let me know. Even if the "issue" seems insignificant. This lib should be bug free.

**Comment by pauloec** [comment]
Thanks for the prompt response!

Month name for the header: for reasons untold, i cannot use header view for month for swipe (there are some logics applied to the month label name), thus i cannot select which month i'm displaying. My work around right now is to change the month when the user taps a day.

But it's simple, just 1 row for days and a month label on top of it. 

I guess you're right, i've used xcode compiler and haven't paid attention, my bad on that.
I might re-test the glitches since delegate wasn't called properly.

**Comment by pauloec** [comment]
One question:
How would be the proper way to implement this: https://www.dropbox.com/s/3atsai4b538to7k/Video%2015-7-19%2019%2048%2027.mp4?dl=0

When the user swipes down, the next day would be selected. But on the last day, it jumps to the next section. Is there a way to achieve this?

**Comment by patchthecode** [comment]
> But it's simple, just 1 row for days and a month label on top of it.

I am not sure if you looked at the [header tutorial](https://patchthecode.com/jtapplecalendar-home/headers/), but there are two ways to create headers.

First is using a **outsideHeader** and the other is using an **insideHeader**. 
Since you just want a simple label, then it looks like you are creating an outsdeHeader (a header that is managed by yourself outside of the scope of this library).

You do this by having a simple headerLabel (like you have done). You change the text of the headerLabel when ever a user scrolls your calendar. You detect when ever a user scrolls the calendar using this function:

```swift
func calendar(_ calendar: JTACMonthView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
    guard let startDate = visibleDates.monthDates.first?.date else { return }
    let dateFormatter = DateFormatter() // Do not declare this here. Use a saved variable. DateFormatter is performance heavy
    dateFormatter.dateFormat = "MMMM, yyyy"
    monthLabel.text = dateFormatter.string(from: startDate)
}
```

**Comment by pauloec** [comment]
Oh! That was what i was wondering! didScrollToDateSegment but i wasn't clear on which date to use from the DateSegment object. That's awesome. I did looked on the header tutorial, but if i'm not mistaken it's written there that a next tutorial would be written for 1 row calendars, thanks for clarifying to me!

Also, i believe the segments were "jumping" from 31 to 1 because i set strict boundaries to true.

Is there a way to prevent user scrolling back when the whole segment is in the past or before startDate?

**Comment by patchthecode** [comment]
ok. im am not sure what you mean. but before i answer, can you confirm that your 1row calendar is configured like this? https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by pauloec** [comment]
It is like this: 
`ConfigurationParameters(startDate:` startDate, endDate: endDate, numberOfRows: 1, calendar: Calendar.current, generateInDates: .forFirstMonthOnly, generateOutDates: .off, firstDayOfWeek: .sunday, hasStrictBoundaries: false)`

What i mean by that is: If the startDate is July 16, the week would start at July 15 and the user wouldn't be able to scroll to week July 14

**Comment by patchthecode** [comment]
Keep in mind that i made this lib as simple as possible. So i do not have functions like this out-of-the-box.
But It is made from a UICollectionView, so making something this is easy.
So you setup a boundary date that you do not want the user to cross.
like this https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by pauloec** [comment]
I see, you have a fair point there.
It seems i have everything sorted out because of your help.

May i suggest some improvements on your tutorials? Sometimes it feels you jump a few steps on the matter. But i should email you directly instead of keeping this conversation here. Again, thank you for your prompt response. I will close this issue.

**Comment by patchthecode** [comment]
you can make the improvement suggestions by opening a new issue here.
Its easier for me to track issues on guthub.
