### ISSUE TITLE
Crash on using NSDate() without a formatter for date ranges

### ISSUE THREAD

**Issue by soundsmitten** [patchthecode/JTAppleCalendar#11]
Under configure calendar, if I make date ranges using NSDate():

```
let currentDate = NSDate()
let startComponents = NSDateComponents
let startDate = calendar.dateByAddingComponents(startComponents, toDate: currentDate, options: NSCalendarOptions())
let endComponents = NSDateComponents()
endComponents.month = 1
let endDate = calendar.dateByAddingComponents(endComponents, toDate: currentDate, options: NSCalendarOptions())
```

I'm getting this error
```
2016-04-29 17:38:30.217 MyApp[81989:679927] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'attempt to scroll to invalid index path: <NSIndexPath: 0x7b073180> {length = 2, path = 0 - 0}'
```

I can work around this if I use the an NSDateFormatter to convert a date into a string, and back into a date. I'm not sure if this is me or the library.

```
let currentDateStr = formatter.stringFromDate(DayService.getFirstDate())
let currentDate = formatter.dateFromString(currentDateStr)!
        
let startComponents = NSDateComponents()
startComponents.month = -12
let startDate = calendar.dateByAddingComponents(startComponents, toDate: currentDate, options: NSCalendarOptions())                
let endComponents = NSDateComponents()
endComponents.month = 1
let endDate = calendar.dateByAddingComponents(endComponents, toDate: currentDate, options: NSCalendarOptions())


```

**Comment by patchthecode** [comment]
Acknowledged. Taking a look

**Comment by patchthecode** [comment]
Some questions:
1. What version are you using?
2. Can you past em the `exact` code you have in that function? The code sniplet you have above has some errors when i pasted it

**Comment by patchthecode** [comment]
Never mind. I think i see your issue. Looking into it

**Comment by patchthecode** [comment]
2 things.

1) The calendar calls the boundary delegates to find out its date boundary. You are supplying `NSDate()` to the boundary. Every time `NSDate()` is called, you are supplying a different date.

Ex.  
> 1st call = 2016-03-01 01:06:03 +0000
> 2nd call = 2016-03-01 01:07:03 +0000

Difference by a ~ second. Since you are changing the boundary, the calendar thinks you want the boundaries updated and the whole layout reloaded. Now while this is logical that the calendar thinks this, it's sort of dumb. 

**I will make the following fix ->** The calendar will only assume that the developer wants to change the date when the difference in the date is greater than 1 day-unit.

2) That being said, the calendar should not have crashed. It crashed because after it assumed number 1 above, it deleted its internal date-data in preparation to generate the new one given by your `NSDate()` function. But it should have done this on the main thread instead of a background one.

The two fixes are done. Testing now. Expect a new code push in a few hrs. In the mean time continue to use the work around. After the fix you should be able to use it like you wanted to.

**Comment by patchthecode** [comment]
Updated to 2.1.1
Can you let me know if you are still having the issue?

**Comment by soundsmitten** [comment]
Yes, 2.1.1 fixes the issue.
