### ISSUE TITLE
When selecting a range programmatically, some reused cells can't be selected

### ISSUE THREAD

**Issue by JSiancas** [patchthecode/JTAppleCalendar#1109]
**(Required) Version Number:**
7.1.7 and 8.0.0

## Description
One of the main features of the app I'm currently working on is to select a whole week when selecting any of its days between Monday and Friday. If one week has been selected previously, it should be deselect after selecting the new week. It works as expected on the current displayed month, but issues start to appear when scrolling to the next months and going back to the first one.

For some reason, there are some specific reused cells (or dates) that can't be selected. They are like two or three per month (different every time) and this occurs only when scrolling. When debugging, I noticed that delegate methods 

- `func calendar:shouldSelectDate:cell:cellState:indexPath: -> Bool`
- `func calendar:didSelectDate:cell:cellState:indexPath:`

are not being called nor those of the UICollectionView.

Is there a way to "reset" the cell's state or something like? `reloadData` doesn't solve this issue.

## Steps To Reproduce

- Select any date (its related week should be selected automatically)
- Scroll to next months
- Select any date of the next months
- A few dates can't be selected

## Expected Behavior
When scrolling to other months, user should be able to select any date and its related week automatically.

## Additional Context
![Screen Shot 2019-08-06 at 4 04 36 PM](https://user-images.githubusercontent.com/1123798/62577200-0a444f00-b864-11e9-9d41-ebb49a247b88.png)
![Simulator Screen Shot - iPhone 5s - 2019-08-06 at 16 05 04](https://user-images.githubusercontent.com/1123798/62577201-0a444f00-b864-11e9-9d09-e72797f83b35.png)
![Simulator Screen Shot - iPhone 5s - 2019-08-06 at 16 05 07](https://user-images.githubusercontent.com/1123798/62577202-0adce580-b864-11e9-9e79-a05bd7fe8e71.png)

**Comment by patchthecode** [comment]
Hi, one thing, when ever showing code, try to paste text instead of a screen shot.
This helps me copy and paste. Right now I can't paste any code from your example to refer to.

> For some reason, there are some specific reused cells (or dates) that can't be selected. They are like two or three per month (different every time) and this occurs only when scrolling. When debugging, I noticed that delegate methods
> ```swift
> func calendar:shouldSelectDate:cell:cellState:indexPath: -> Bool
> func calendar:didSelectDate:cell:cellState:indexPath:
> ```
> are not being called nor those of the UICollectionView.

Then i think there is some bigger problem at play here.
Is it possible you can provide an empty sample project (without companycode) which recreates this problem? or is your project sharable?

**Comment by JSiancas** [comment]
Sure. Sorry for that. I'll work on a sample project. Give a couple or hours. Thank you!

**Comment by JSiancas** [comment]
Hi. Here is the sample project. As I'm changing the font for selected cells, I'm forcing not to reset them to have regular font. This way can you identify some specific cells which don't respond when tapping it. This usually replicates the issue mentioned above.

Let me know if you need something else.

[JTAppleCalendarSample.zip](https://github.com/patchthecode/JTAppleCalendar/files/3477359/JTAppleCalendarSample.zip)

**Comment by JSiancas** [comment]
Please, also notice the calendar has a weird behavior when changing the value for `numberOfRows` to 5.

**Comment by patchthecode** [comment]
ok will check this out today after work

**Comment by patchthecode** [comment]
I think you might have had some logical errors.
I fixed.
Just replace your files with these.

I would have given you the whole zipped project. but I use Xcode 11 Beta, and it may not have opened on your system.
Let me know how it goes.
[files.zip](https://github.com/patchthecode/JTAppleCalendar/files/3479411/files.zip)

**Comment by patchthecode** [comment]
Also, setting it to 5 rows is expected. If you unhide your hidden cells, you'll see that there are cells there.

It looks like what you wanted is not 5 rows. You want adjustable rows. 
You want 6 rows when the month requires 6, and 5 rows when the month requires 5.

Did you take a look at the tutorials before you began? https://patchthecode.com

**Comment by patchthecode** [comment]
If your issue is resolved. you can close this

**Comment by JSiancas** [comment]
Hey, can you please give more details about this `I think you might have had some logical errors`? I would like to know what logical you are referring to. Thank you for your time.

**Comment by patchthecode** [comment]
First,
Is your issue resolved with the files i gave you?

**Comment by JSiancas** [comment]
Hey, I have been testing your fix and it looks like it's working fine now. Thank you for your time, I appreciate it. By the way, I would like to know the difference between what you did and what I did. Not so easy to notice it.

**Comment by patchthecode** [comment]
Well, i didn't go through all your logic, but i saw you were using the flag to check  to see if a tap was `userInitiated`. And i also saw the you were deselecting in the `didDeselect` and selecting in the `didSelect` function without the `triggerSelectionDelegate` being set to false. This made tracking the logic of the code difficult and i had to set many break points every where just to follow the code flow. 

Therefore i suspect that there was an error in logic in there.

So instead of debugging the code, i just made it simpler. That way, it is easy to see where the logic breakdown. But after making it simpler, the issue went away, which leads me to believe that it was in-fact an error in logic.

In order to 100% confirm that, however, i'd have to go through your unmodified code entirely, and that would be too time consuming for me.
