### ISSUE TITLE
Missing date when user select different region on device.

### ISSUE THREAD

**Issue by jinjin-lee** [patchthecode/JTAppleCalendar#1156]
Hello.
I am using JTAppleCalendar in my project and it works well.
But I found big issue a few days ago. When I select different region on my device, calendar is showing missing date.
For example, I am in China and if I select region to Netherlands from China on my device then calendar is showing missing date. I added image.
Please check this asap.

- This correct date. (in my region)
![Screen_Shot_2019-10-14_at_5_57_30_PM](https://user-images.githubusercontent.com/35056128/66743544-bc277980-eeac-11e9-9cb6-0b1457893369.png)

- This is incorrect date.(in Netherland region)
![Screen_Shot_2019-10-14_at_5_59_06_PM](https://user-images.githubusercontent.com/35056128/66743625-f133cc00-eeac-11e9-8eb9-808a2284cf3c.png)

Thanks and Regards.

**Comment by patchthecode** [comment]
Can you help me reproduce this on simulator?

What code do you have in your configureCalendar function/

**Comment by jinjin-lee** [comment]
Thanks for your response.

Please go to Settings -> General -> Language & Region -> Region -> Change to Netherland.
And please check JTAppleCalendar app. then you can see issue.

Regards

On Oct 14, 2019, at 6:31 PM, JTAppleCalendar <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you help me reproduce this on simulator?

What code do you have in your configureCalendar function/

**Comment by jinjin-lee** [comment]
Hello How are you?
Could you reproduce issue and check it?
Regards.

**Comment by patchthecode** [comment]
What code do you have in the `configureCalendar` function?

**Comment by jinjin-lee** [comment]
![Screen Shot 2019-10-15 at 5 24 21 PM](https://user-images.githubusercontent.com/35056128/66818930-ad09ff80-ef70-11e9-863b-362f2482231e.png)
This is configuration.

**Comment by patchthecode** [comment]
I have a sample app attached to the github of JTAppleCalendar.
This is not happening in the sample app.

What I would tell you is this, dates are not "missing", what you are seeing is the dates being offset by one. What you are experiencing is a time zone issue.

Is it possible you can provide some sample app that reproduces this on simulator?

**Comment by jinjin-lee** [comment]
Hi This is not date offset.
This week day offset.

**Comment by patchthecode** [comment]
For me, date offset = week day offset. They are mean the same thing to me.
Can you try to answer my question instead of trying to make a correction to the sentence?

**Comment by jinjin-lee** [comment]
[Screen Recording 2019-10-15 at 6.08.15 PM.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/3728640/Screen.Recording.2019-10-15.at.6.08.15.PM.mov.zip)

**Comment by patchthecode** [comment]
[screen.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/3728828/screen.mov.zip)
This is not happening for the sample code.


Can you give me a sample app which reproduces this?
Do not give me your app code, I want a new empty sample app only with your calendar code.
I do not want any of your secret app code. I only need code that relates to the calendar.

If you can get me this sample app, then I can tell you what your problem is.

**Comment by jinjin-lee** [comment]
Hi
This is my test sample code which you can reproduce issue.
[TestCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3732189/TestCalendar.zip)

**Comment by patchthecode** [comment]
ok. Thank you. 
i'll look at this in the morning

**Comment by jinjin-lee** [comment]
Hello How are you?
Did you check my sample code?

**Comment by henriqueG** [comment]
We're also having this problem here (with Brazil region set on device/simulator). 

After trying a bit (and digging in the lib's code), I started to pass the `firstDayOfWeek` as Sunday in my `ConfigurationParameters` and it fixed for me

Ours are now: `let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate, firstDayOfWeek: .sunday)`

**Comment by patchthecode** [comment]
@henriqueG  Thank you so much for looking into this. You saved me a lot of debugging time.

@jinjin-lee, based on what @henriqueG has found -->
In your code you had this for the configure calendar function.
```swift
extension ViewController: JTACMonthViewDataSource {
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        return ConfigurationParameters(startDate: Date(), endDate: Date())
    }
}
```

You did not provide a calendar. Therefore the library will use the default calendar of your phone.
This default calendar will have have the default region, and default settings.
My guess is that in the Netherlands, the default setting is for start-of-week is Monday instead of Sunday. Therefore, when you changed your calendar region to Netherlands, the date shifted one to the left.

To fix the issue, you can do two things.

1) Explicitly set your start of week in the `configureCalendar` function.
2) Have a dynamic header - Instead of having a static `Sun|Mon|Tue|Wed|Thu|Fri|Sat`, you can detect what is the default start week for your region, and make your header change to match it.

**Comment by patchthecode** [comment]
closing this issue. Let me know if you are still stuck.
