### ISSUE TITLE
Assertion failed: Error, your start date cannot be greater than your end date

### ISSUE THREAD

**Issue by jovdelfin01** [patchthecode/JTAppleCalendar#1205]
**(Required) Version Number:**
8.0.2

## Description
Assertion failed: Error, your start date cannot be greater than your end date
: file /Users/-myname-/Documents/DisDentsAdminApp/DisappearDentsAdminApp/Pods/JTAppleCalendar/Sources/JTAppleCalendar/JTACMonthActionFunctions.swift, line 135
2020-01-04 20:22:35.781704+0800 DisappearDentsAdminApp[2148:610222] Assertion failed: Error, your start date cannot be greater than your end date
: file

## Steps To Reproduce
I use this function to get the month's first date

collectionView.visibleDates { (visibleDates) in
       // Erroring on the visible dates method and not event getting here.
            self.setupViewsOfCalendar(from: visibleDates)
        }

Collection view is of type JTACMonthView 

## Expected Behavior
I have been using this before and i'm only getting this problem starting 2020.

**Comment by patchthecode** [comment]
is your start date cannot be greater than your end date?

**Comment by jovdelfin01** [comment]
that's the thing i didn't put any data in this. It used to work suddenly
it's 2020 and it doesn't work anymore

**Comment by patchthecode** [comment]
When the assert crash happens, can you inspect your start and end date to see what they are?
Put print statements.
Because that assert was placed there specifically if your start date is greater than your enddate.

**Comment by jovdelfin01** [comment]
This is what shows up to my xcode console with the config parameter
containing the startdate and enddate being nil

**Comment by patchthecode** [comment]
-> config parameter

What is nil, the `enddate`, `startdate` or `configParameter`?
And why is it nil?

**Comment by jovdelfin01** [comment]
I have no clue. I haven't changed anything since updating from version 7 to
version 8. It just started not working without me changing anything. Where
is the data supposed to come from?

**Comment by patchthecode** [comment]
ok, i'll be clearer.
I didnt write your code. So I do not know where to start at all.
The fact that ti worked before, and then stopped working, lets me now that you have coded something for a specific date range. And then as soon as 2020 reaches, it fails.

So can you tell me what data you used to setup the calendar?
What have you set as your start date and end date?

**Comment by AbdulJaf** [comment]
is this error fixed?

Im still having this error don't where the end date is getting its data!

**Comment by patchthecode** [comment]
Can you tell me what you used to setup the calendar? I need to see code

**Comment by AbdulJaf** [comment]
<img width="1219" alt="Screenshot 2022-06-23 at 10 55 58 AM" src="https://user-images.githubusercontent.com/95210198/175222618-83304c5b-7968-43db-ba0e-547d99727879.png">
<img width="1328" alt="Screenshot 2022-06-23 at 10 56 25 AM" src="https://user-images.githubusercontent.com/95210198/175222640-be88d440-6bf5-45f0-a94a-62dce6bf3e03.png">

While clicking on calendar button its crashes and having above error message. Can't able to change the end date which is in particular date of 2020-02-27 18:30:00 that should be above the current date!

Don't know whats the problem here, but I'm sure its coming from POD file!!!



![Screenshot 2022-06-23 at 11 16 01 AM](https://user-images.githubusercontent.com/95210198/175224342-a79edf3b-f2f2-4c29-bcfc-f0664ba21dfe.png)


Even if I hide that line particular line I receive another error and also even I this error all error are gone but the calendar is not loading!

**Comment by patchthecode** [comment]
Hello, I think you misunderstood my question. Let me re-phrase it another way.


If you look at the [tutorial here](https://patchthecode.com/jtapplecalendar-home/calendar-from-scratch/), it will show you all the parameters you need to properly setup the calendar.  There is a `startDate` and a `endDate`.

So, can you show me the code where you instantiate your calendar?

**Comment by AbdulJaf** [comment]
Im sorry, It was my mistake. I was passing end date with my server API that is locked on 2020. 

And thanks a lot!

**Comment by patchthecode** [comment]
cool
