### ISSUE TITLE
v8.0.3 with deployment target <10.0

### ISSUE THREAD

**Issue by p-nicolaou** [patchthecode/JTAppleCalendar#1212]
## Description
Our project is set to deployment target iOS 9.0. It has been migrated to Swift 5. However, we are not able to update JTAppleCalendar to latest Pod as the deployment target has been set to iOS 10.0.
Due to business requirements, we can't change our project's deployment target (yet). Any workarounds?

**Comment by patchthecode** [comment]
hmm... this is hard for me to do..
I deprecated 9.0 because that was too many iOS versions for me to track.

The only worl around would be to use the latest, and build it for iOS 9.

then when it breaks, (i think it should break in 3-4 places if i remember correctly), try to make that iOS 10+ work for iOS9 but adding @available tags... :s
