### ISSUE TITLE
Package compile error with SPM

### ISSUE THREAD

**Issue by SajjadKharrazi** [patchthecode/JTAppleCalendar#1267]
hi
i fetched `8.0.3` version with `SPM` and everything worked great.
but when i am working with Xcode, i have always these errors in Issue Navigator:

![image](https://user-images.githubusercontent.com/7239983/81564495-13db8400-93ad-11ea-81c2-5bf58b53b04c.png)

i can compile my app and it shows calendar correctly but with these errors...

**Comment by patchthecode** [comment]
Looks like you are building for a lower version than JTAppleCalendar supports.

**Comment by SajjadKharrazi** [comment]
no, my iOS deployment target is 11.0

**Comment by patchthecode** [comment]
hmm.. but it says tvOS, not iOS.

The error message says that JTAppleCalendar's function are only available for tvOS 10.0 and newer.

This would imply that you are building on a lower tvOS version that JTAppleCalendar supports?

Are you building a tvOS build target with a version less than 10.0 ?
I am asking this because this what the error message implies.

**Comment by SajjadKharrazi** [comment]
![image](https://user-images.githubusercontent.com/7239983/81597295-c5dd7500-93da-11ea-98c5-b761c5c2c711.png)


this is my build setting options.  but i don't have any plan to develop for tvOS.
also i should to tell you that when i closed Xcode and open it again, these errors disappeared :)

**Comment by patchthecode** [comment]
awesome.
ok... so that was just some XCode bugs.
Will close this
