### ISSUE TITLE
didSelectDate is not called

### ISSUE THREAD

**Issue by trankhanhloc3605** [patchthecode/JTAppleCalendar#1289]
Version: JTAppleCalendar (8.0.2)

**(Required) Version Number:**

## Description
function didSelectDate is not working with me, please help me. thanks
## Steps To Reproduce
        calendarView.calendarDelegate = self
        calendarView.calendarDataSource = self

**Comment by patchthecode** [comment]
Have you followed the examples on patchthecode.com ?
We have examples there already built

**Comment by dmitchl** [comment]
I had the same problem after migration to 8+ version.
The problem was in method signatures.
In 8+ version new parameter (indexPath: IndexPath) is added to **didSelectDate** method. So
`func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState)`
become
`func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath)`

**Comment by patchthecode** [comment]
closing this issue.
Assuming resolved.

If you still have issues then let me know.
