### ISSUE TITLE
Assertion failed: file JTAppleCalendar/JTACMonthActionFunctions.swift, line 43

### ISSUE THREAD

**Issue by julianiaccopucci** [patchthecode/JTAppleCalendar#1298]
**(Required) Version Number:** 8.0.3

## Description
Error this should not be nil. Contact developer Jay on github by opening a request
There was an error in this code section. Please contact the developer on GitHub

## Steps To Reproduce
I called layout subviews on my view controller.
I've been using the calendar for a while but it's the first time I see this happening. Hard to replicate!

## Additional Context

Stack trace https://pastebin.com/fuAc8Xb0
![Screenshot 2020-10-21 at 11 53 57](https://user-images.githubusercontent.com/5910320/96710522-1ac2e580-1394-11eb-9d72-2a42f310c4c8.png)

**Comment by patchthecode** [comment]
Its a assert error that i have  in the code. It will not crash in prod because its simply an assert and not a fatal error.
However, it does alert the developer that something is potentially wrong.

This usually happens when the Calendar's frame is .Zero, or .hidden = true
Are you doing something like this?
If there error happens again, then can you go up the stack trace until you see the .frame of the calendar.

To find the error instantly, can you put a breakpoint inside the `dateOwnerInfoFromPath` function and see why it is returning nil?  Because this is why it is causing as Assert error. The `dateOwnerInfoFromPath` function is returning nil.

**Comment by espitia** [comment]
@patchthecode I am having the same issue. It has something to do with iOS 14.1 because the crash is non-existent on pervious iOS versions (tested 13.6 and below). Accordingly, it only appeared after upgrading to Xcode 12 + iOS 14.1 simulators.

**Comment by patchthecode** [comment]
I'll be updating to iOS 14.1 soon. I am currently on iOS 14.0

**Comment by patchthecode** [comment]
this should have been fixed now. latest version is 8.0.5
