### ISSUE TITLE
JTAppleCalendar new version

### ISSUE THREAD

**Issue by ppluskota** [patchthecode/JTAppleCalendar#1301]
First of all - thanks for this amazing library it's making my life easier
I have a question - when there will be a new version of JTAppleCalendar? I noticed that the latest commit was almost half a year ago and there are already over 70 reported issues.

**Comment by patchthecode** [comment]
There are 70 reported issues.
But there are very few major ones.

I will always fix any major issue facing this lib for the forseeable future.


For the many issues here however,
Many of the issues are feature requests and questions on "how this unique thing" can be done.
For this I would really like people to do pull requests.

If you have a major issue that can be reproduced, then just file a request and i'll have a look.
Just make sure it is 

1. reproducible
2. have sample code (the minimal code without all your company code)

Since a new iOS version came out, i'll have to do some updates soon. I've seen some people reported an issue, but as I havent downloaded the new Xcode yet, I havent had time to take a look.

**Comment by ppluskota** [comment]
Thanks for the quick answer. Keep up the good work. I'm closing this one
