### ISSUE TITLE
Text of cellState VS the date, is different?

### ISSUE THREAD

**Issue by dajun-whisper** [patchthecode/JTAppleCalendar#1359]
Version Number:8.0.4

Why is the text of cellState different from the date?

//print message----

CellState(isSelected: false, 
                 text: "8", 
                 dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, 
                 date: 2022-08-7 16:00:00 +0000, 
                 day: JTAppleCalendar.DaysOfWeek.sunday, 
                 row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), 
                 selectionType: nil)

the text is 8 and it's correct, but the date is 2022-08-7, was there something i ignored?

**Comment by patchthecode** [comment]
The text is correct. Thats good.

Now for the date. I guess you printed it on console to get `2022-08-7` ?
If this is what you did, then may get correct/incorrect result. This is the nature of dates in swift for any app.

Why?
Because the print command has its own date formatting under the hood. So if you live in a time zone in the west near Apple's headquarters, you get a different result than printing a date if you live in the east half of the world (different timezone).

So whats the best way to actually print a date? Use a NSDateFormatter with the correct timezone settings, because you may/may not get correct results if you just print a raw date to console.

This is explained extensively here -> https://github.com/patchthecode/JTAppleCalendar/issues/252
