### ISSUE TITLE
overriding scrollViewWillEndDragging for fast scrolling

### ISSUE THREAD

**Issue by colditz18** [patchthecode/JTAppleCalendar#172]
Hi, I want to know if it is possible, and in case it is, how to do it, to override the method scrollViewWillEndDragging. I need to do this because I want to do some UI updates before scrollViewDidEndDecelerating gets called, for example, when user makes fast scrolling. Is there any way to do this? 
Thanks and congratulations for this great work!

**Comment by patchthecode** [comment]
Thanks.
Which version are you using? 5.0.1 or 6.0.0 ?

If you're using version 6.0.0, then there has to be an upgrade to it for it to happen.
Can you do a pull request and submit it? I will approve it.

Here is the change you need to do -->
in the `UIScrollViewDelegates.swift` file, you will see a function called

```swift
 public func scrollViewWillEndDragging(_ scrollView: UIScrollView,
        withVelocity velocity: CGPoint,
        targetContentOffset: UnsafeMutablePointer<CGPoint>)
```
all you have to do is change it to this and submit a request. That's it for the library side of things.

```swift
 open func scrollViewWillEndDragging(_ scrollView: UIScrollView,
        withVelocity velocity: CGPoint,
        targetContentOffset: UnsafeMutablePointer<CGPoint>)
```

Now in your code, you just have to create your own custom calendar and use it (instead of mines), and override that function. Thats it.

For example you would my use this as your calendar:

```swift
class myCustomCalendar: JTAppleCalendarView {
    public override func scrollViewWillEndDragging(_ scrollView: UIScrollView,
                                          withVelocity velocity: CGPoint,
                                          targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        print("This will be executed before my didEnd code")
        super.scrollViewWillEndDragging(scrollView, withVelocity: velocity, targetContentOffset: targetContentOffset)
        print("This will be executed after my didEnd code")
    }
}
```

You will now need to use `myCustomCalendar` in your app. Change the calendar type on Storyboard to your new `myCustomCalendar` type. And make sure you delete the `module` text as shown below.

<img width="1009" alt="screen shot 2016-10-19 at 2 10 04 pm" src="https://cloud.githubusercontent.com/assets/2439146/19567114/82aa63b8-96a1-11e6-80d5-3d0cf52e60ed.png">

Also, if you're using version 5.0.1, you need to do the same steps. The might be a little different because `5.0.1` is in swift 2 while `6.0.0` is in swift3. In you're using `5.0.1` however, you do not need to do a pull request.

Finally, please leave a star rating on this repository if it has help you in anyway. Its needed for this project :)

**Comment by patchthecode** [comment]
Some time has passed and no response. I will assume this is corrected.
If you are still having issues, then feel free to re-open this request.

**Comment by colditz18** [comment]
sorry for not responding. Finally I got to do what I was trying by adding a different header than I had previously. Thank you anyway

**Comment by patchthecode** [comment]
Cool. Have a good one.
