### ISSUE TITLE
Thread1 : Signal SigABRT

### ISSUE THREAD

**Issue by HumayunKaleem** [patchthecode/JTAppleCalendar#219]
Hello,

For some reason i am not able to run the project. I have followed the whole guide of installation as well. But after attaching it abort with payload error. I have checked the Xib name as well and have followed the instructions carefully.
Attaching the Project here.
[JTCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/629386/JTCalendar.zip)

Deployment Target 10.1
Xcode 8.0

Thanks.

**Comment by patchthecode** [comment]
@HumayunKaleem checking it out now. sec

**Comment by patchthecode** [comment]
@HumayunKaleem I do not know how you ended up in that state. I see youre doing some interesting things in your code.

Can you do this?

1) Create an empty project
2) Go to your console.
3) Go to the path where your XCode project is
4) run `pod init`

This should create a file in that location called `Podfile`

5) modify the `Podfile` to include the `JTAppleCalendar` pod
6) run pod install

This should install the pod. And install the `Xcode Workspace file`

7) Close the project.
8) Repoen the project using the `XCode Workspace file` (not the project file)
You will now be using the `XCode Workspace file` to open your project from now on. This is how Cocoapods work

9) Go to you `ViewController.swift` file

and put this in your code
`import JTAppleCalendar`

10) Build and run your application.

If this works, then your issue is resolved and maybe some mistake was made the first time. 
If this does not work, let me know. Or join me in chat here -> https://gitter.im/patchthecode/JTAppleCalendar

I'll be awake in 8hrs from the time of posting this message though :)

**Comment by HumayunKaleem** [comment]
I was not installing the pods in the main directory rather in the Tests and UITests of my project.

**Comment by patchthecode** [comment]
cool awesome. And thanks!

**Comment by D2Jgs** [comment]
I am having a sigabrt error too. Here is the code; i followed your video and made it.

import UIKit
import JTAppleCalendar

class hallAvail: BaseViewController {
let formatter = DateFormatter()
    override func viewDidLoad() {
        
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        self.addSlideMenuButton()
        self.title = "Hall Availibilty"
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}
extension hallAvail : JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource{
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        
    }
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2017 01 01")
        let endDate = formatter.date(from: "2017 31 01")
        let parameters = ConfigurationParameters(startDate: startDate!, endDate: endDate!)
        return parameters
    }
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.dateLabel.text = cellState.text
        return cell
    }
}

**Comment by patchthecode** [comment]
@D2Jgs do you have a sample app on github i can take a look at?

**Comment by D2Jgs** [comment]
No i dont

**Comment by D2Jgs** [comment]
What do you want me to do ?

**Comment by patchthecode** [comment]
i need a sample app with the error you are experiencing.
i cannot tell from the message you have posted.
patchthecode@gmail.com

**Comment by D2Jgs** [comment]
I emailed you a project.

Thanks for the help.

**Comment by patchthecode** [comment]
file fixed. and sent by email.

**Comment by D2Jgs** [comment]
Thanks it worked!!!
