### ISSUE TITLE
Wrong cell placement when generateInDates == InDateCellGeneration.off

### ISSUE THREAD

**Issue by twiedow** [patchthecode/JTAppleCalendar#285]
When I set generateInDates to .off the placement of the cells always starts in row 0, column 0.
When in-dates are shown the placement is correct.

View with generateInDates = .off
<img width="243" alt="screen shot 2017-02-02 at 12 00 12" src="https://cloud.githubusercontent.com/assets/656549/22546926/713766b2-e93f-11e6-8b62-13232c8cdd23.png">

View with generateInDates = .forAllMonths
<img width="235" alt="screen shot 2017-02-02 at 11 59 36" src="https://cloud.githubusercontent.com/assets/656549/22546943/86f7fce6-e93f-11e6-8468-f05acadea45e.png">

**Comment by twiedow** [comment]
As workaround I set generateInDates = .forAllMonths but set an empty string when the date is not in the current month.
But it would be better to fix this bug :-)

**Comment by patchthecode** [comment]
@twiedow ah. This is not  a bug, this is expected. Check out the documentation here -> https://patchthecode.github.io. And your question is answered specifically on this link -> https://patchthecode.github.io/CalendarLayout/.   If the tutorial is not clear, then let me know so that I enhance it ok.

Setting indates to `off` will cause them to not be generated. Thereby changing the offset of your calendar

What is the intention of your configuration?
Do you want indates to be generated but invisible? OR
Do you want indates to be totally not generated.

Do you want

**Comment by twiedow** [comment]
OK, i thought this is a bug. Actually I don't need them to be needed generated, I just need the offset. But if this works as designed, I want them to be invisible. Is there a different way or do I have to do it manually by configuring my cell?

Anyway, I don't really get the use case where I don't want the in dates to be generated and have the cells always starting in cell 0;0. Can you give me an example where I might need it?

**Comment by patchthecode** [comment]
This lib is capable of building any calendar in any style ->> So longs as it is a grid calendar.
If you want them to be generated but invisible, then all you do is configure it to be invisible -> https://patchthecode.github.io/DateCellConfiguration/

> Anyway, I don't really get the use case where I don't want the in dates to be generated and have the cells always starting in cell 0;0. Can you give me an example where I might need it?

Layouts vary a lot. You will be surprised. 
If you tell me how you want your calendar to look, I can tell you a configuration.
