### ISSUE TITLE
selectedView is not completely circular

### ISSUE THREAD

**Issue by DaewoonKim** [patchthecode/JTAppleCalendar#299]
Hi,
I followed the tutorial to make circular selectedView, but found something strange.
I set selectedView's width and height to 30 in Xib and in code I gave it cornerRadius of 15.
I expected it would be a circle. 
It looks like a circle, but some sides like top, bottom, left, or right isn't very circular.
It looks like circle is cut somehow.
I saw many calendar images created by using JTAppleCalendar from other developers, but I found some images too have not fully circular selectedViews.
Is there any way to solve this problem?
 
![img_1228](https://cloud.githubusercontent.com/assets/15996563/22775095/749323e2-eeed-11e6-8b54-1e362067d9c7.jpg)

Thank you

**Comment by patchthecode** [comment]
looks like your circle is being cut by the size width/height

Let's test it to see if this is the problem.
Try width 26/ radius 13.
Is it a circle now?

**Comment by DaewoonKim** [comment]
I tried set width 26, radius 13, but it is the same.
My autolayout is like below just in case it is wrong.
<img width="1170" alt="2017-02-09 17 50 28" src="https://cloud.githubusercontent.com/assets/15996563/22775761/6c497468-eef0-11e6-8d17-bf32f5218929.png">

**Comment by patchthecode** [comment]
hmm.. i think mines look ok

<img width="505" alt="screen shot 2017-02-09 at 12 57 51 am" src="https://cloud.githubusercontent.com/assets/2439146/22776005/e23e3bb0-ee62-11e6-8f23-92f720c9d3b3.png">


Have you set the item size of the calendar? or no?

**Comment by DaewoonKim** [comment]
Yours look ok.
No, I didn't set the item size.

**Comment by patchthecode** [comment]
Is it possible you can provide your code zipped ?

**Comment by patchthecode** [comment]
will check in the morning. heading to sleep. have a good one,

**Comment by DaewoonKim** [comment]
Ok, I'll send you a mail before you wake up :)
Thank you !

**Comment by DaewoonKim** [comment]
Hey, I just fixed the problem by using UIImageView in xib and a circle image file.

**Comment by patchthecode** [comment]
@DaewoonKim thanks man. I was digging deep trying to find the solution to the problem. I do not think that this problem is caused by the calendar. But I'm glad you found a work around. Now I can help others.

**Comment by DaewoonKim** [comment]
I also want to say thank you for your hard work. It really helps me save a lot of time!

**Comment by patchthecode** [comment]
cool. If you have any other issues. Then let me know.

**Comment by gmoraleda** [comment]
Same issue here. First one looks cut on the left and bottom margins.
Second date looks just fine. Did you find a solution to this problem (using UIViews and cornerRadius) ?

Thanks a lot for your great work. Really.

![not round](https://cloud.githubusercontent.com/assets/25835012/24828993/b9a52c0e-1c93-11e7-8216-6f9e331c5bc3.png)
![round](https://cloud.githubusercontent.com/assets/25835012/24828992/b9a2cdc4-1c93-11e7-9319-e5921358a70e.png)

**Comment by patchthecode** [comment]
@gmoraleda Does this happen on the actual device? Or does it only happen on the simulator?

There is one thing to note however. This is not caused by the calendar library. This is caused by the UICollectionView itself based on the size of the view, and based on the size and offset of the cells.

I have created a sample project with a UICollectionView (not the calendar library). The sample project contains a `UICollectionView` with no changes or modifications. And I am still seeing the circle view cut on the top sides.

<img width="462" alt="screen shot 2017-04-08 at 9 18 12 am" src="https://cloud.githubusercontent.com/assets/2439146/24830500/61a80d34-1c3c-11e7-8507-adb6a6bbbadc.png">

<img width="406" alt="screen shot 2017-04-08 at 9 18 33 am" src="https://cloud.githubusercontent.com/assets/2439146/24830498/5d1b4e52-1c3c-11e7-8a08-0fdb1e9cb1e8.png">

Here is the project so you can see for yourself -> [testCollectionView.zip](https://github.com/patchthecode/JTAppleCalendar/files/907606/testCollectionView.zip)

As can be seen here, it does not seem to be a problem of the calendar library.
I do not do anything that manipulate the views in the library, i use exactly what i get from the UICollectionView. 

What users have found to work around the problem was using an Image. That way, a view does not have to be rendered using layers. It will be displayed correctly one time, every time.

If you have more information as to why this may be happening then do let me know. Because all my investigations (for now) tells me that it is caused by the collection view.

**Comment by gmoraleda** [comment]
It happens on a real device as well on the simulator.
I'll use images instead of UIViews. Thanks for your reply :-)
Cheers.
