### ISSUE TITLE
How can I add custom design for some dates?

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#3]
Hi again,

my calendar will show circle (or something else) on some dates in future based on my calculations in my ViewController. How can I apply custom styling within my function for calculations for certain dates?

**Comment by patchthecode** [comment]
If you already know how to create an design a UITableView, this the idea is very similar. I have done a tutorial there on how to design the cell entirely how you want. Have you looked at the tutorial in the documentation yet?

**Comment by antonijap** [comment]
I have my custom CellView.xib and .swift but how do I fire up different, let say, background based on calculations in Calendar view controller? In my Calendar view controller I have one function that calculates set of dates in future (based on what user tapped), and there I need to apply certain design for those future dates. Is that possible?

**Comment by patchthecode** [comment]
Yes. It is possible. Do you know how to setup views for a UITableViewCell? If you wanted to setup background view for your tableViewCell, doing so would be the exact same way to do it using your calendar CellView.xib. 

It is Just like you did in the tutorial for the UILabel (which displayes the dates). Simply go to your CellView.xib and drag a UIView unto CellView.xib

Now lets say you wanted the background to be Green. Then set the background of the view that you just dragged unto the xib to the color green. Since you want this view as the background, you want to do 2 things: 

1. set its autolayout constraints to full out the entire background of the cell.
2. set the **position** of the CellView to be **behind** all the other views on the CellView.xib
3. set visible = hidden (we'll do this because you said that you only wanted it to be displayed based on some calculation

Now that you have your backgroundView, lets head over the the CellView.swift. Now create a new @IBOutlet for the backgroundView just like you did for the UILabel for the date display in the tutorial. Now in that file, create your new function that will set the visibility of the backgroundView to true (or false) based on your calculation.

This is exactly the way a UITableView is setup.

**Comment by antonijap** [comment]
I stuck at the last step. I'll try to make appropriate function. Thanks.

**Comment by patchthecode** [comment]
The sample app has an example of how it makes the backgroundView visible/hidden
