### ISSUE TITLE
Discussion best way to handle selectedPosition() for range selection

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#318]
<img width="286" alt="screen shot 2016-04-07 at 9 49 29 am" src="https://cloud.githubusercontent.com/assets/2439146/23177954/8f30e566-f81d-11e6-9927-baa143d949af.png">

`Yellow` = Left
`Blue` = Middle
`Red` = Right
`Green` = Single

**Comment by patchthecode** [comment]
@tungfam i am having some problems the solution we mentioned last time.
According to what you have told me last time, the 27th on the 2nd month should also be colored `Blue` instead of yellow.

The problem with this solution is, if two months are displayed on the screen at the same time, then it will look weird as the image shown up above. 

I was thinking that it would be best if `generateInDate = .forFirstMonthOnly` might be a better solution?

**Comment by tungfam** [comment]
@patchthecode hmm actually the issue is solved. there is no more issue with that 1st May. and that is thanks to `generateOutDates: .tillEndOfRow` (do you remember i asked in gitter how to make 5 rows when 6th is not needed? and you suggested doing this and it basically solved 2 issues that i had) 

so all good now :) thanks a lot!

**Comment by patchthecode** [comment]
awesome. closing this issue now.
