### ISSUE TITLE
Errors since updating

### ISSUE THREAD

**Issue by lee493** [patchthecode/JTAppleCalendar#377]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.1
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

Hiya, I've just updated my pods and downloaded 7.0.1. 

This has caused an array of errors such as "use of unresolved type JTAppleDayCellView" , there is no member for registerCellViewXib or cell inset.
 calendarView.dataSource = self and calendarView.delegate = self are also producing errors. 
To be clear, these errors were not appearing before the update and I cannot see any posts which indicate these values should be changed post update. Thanks for your help

**Comment by danlozano** [comment]
Hi.

- JTAppleDayCellView is now JTAppleCell
- calendarView.dataSource and calendarView.delegate is now calendarView.calendarDataSource and calendarView.calendarDelegate.

Many things are different now in the new version, one thing that helped me a lot was this video since there is no new documentation yet, I think.

https://www.youtube.com/watch?v=zOphH-h-qCs

**Comment by lee493** [comment]
Okay thanks a bunch, I literally just found this page which was helpful for converting to the update.

However now when I run the calendar view I am getting an error on the line 
setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol)

I'm not receiving an error message in the terminal but the line is saying EXC_BAD_ACCESS. Any ideas?

https://github.com/patchthecode/JTAppleCalendar/blob/master/Example/JTAppleCalendar%20iOS%20Example/ViewController.swift

**Comment by danlozano** [comment]
I had that error as well.

The reason is because the calendar changed quite a bit, and now the collection view is exposed to us.

If you follow the youtube video instructions that error will go away.

**Comment by lee493** [comment]
I followed the instructions previous issue. Updated the podfile to pod 'JTAppleCalendar', '~> 7.0'.
Also followed the tutorial but still getting errors elsewhere. The initial issue is however fixed

**Comment by patchthecode** [comment]
I have not yet finished the transition guide.
But if you let me know where the errors are then I can help

**Comment by kermankohli** [comment]
Hey getting the same error at setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol). I've attached the subclass of the implementation below :)
 
[HW_Calendar.swift.zip](https://github.com/patchthecode/JTAppleCalendar/files/917779/HW_Calendar.swift.zip)

**Comment by patchthecode** [comment]
@kermankohli i'll look at this after work. Thanks for the file.

**Comment by patchthecode** [comment]
@kermankohli i am not understanding the code a bit.
Why are you creating a subclass of JTAppleCalendarView?
and where is this function called
```swift
func setupDateSelector(forRows: Int, scrollingMode: ScrollingMode) 
```

**Comment by kermankohli** [comment]
@patchthecode I'm creating a subclass of it since there's a bit of customisation that I'm doing and showing this customised calendar in two places. Here's an example of how I'm using it in another controller:

` override func viewDidLoad() {
        super.viewDidLoad()

        calendarView.setupDateSelector(forRows: 4, scrollingMode: .stopAtEachSection)
        calendarView.extendedDelegate = self
        calendarView.startAtFirstOfMonth = false
 calendarView.updateMonthText = { [weak self] text in
            self?.monthLabel.text = text
        }
        
        calendarView.dateSelected = { [weak self] in
 self?.tableView.reloadData()
        }
 }`

**Comment by patchthecode** [comment]
@kermankohli ok, i will have another look after work today

**Comment by zjdavid** [comment]
I have the same issue.

I followed the youtube video instructions step by step but the error doesn't go away.

**Comment by patchthecode** [comment]
Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
@zjdavid Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

The issue the others are mentioning is different. @kermankohli has done some code that is totally different from the video. 
Can you provide a zipped copy of the project for me in here? just drag the file inside the chat box.

**Comment by patchthecode** [comment]
@kermankohli able to talk? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing this issue as all seem to have been resolved.
If there are still issues here, then reopen, and I  will help.

**Comment by oskarko** [comment]
I'm getting the same error. Any ideas?

**Comment by patchthecode** [comment]
@oskarko what errors?

**Comment by oskarko** [comment]
"However now when I run the calendar view I am getting an error on the line
setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol)

I'm not receiving an error message in the terminal but the line is saying EXC_BAD_ACCESS. Any ideas?

"

**Comment by patchthecode** [comment]
ok. first, you'll have to tell me what version of the calendar you are using.

What do you have in your Podfile?
Also, how are you creating your calendar, with code? or with Interface Builder?

**Comment by oskarko** [comment]
I have RealmSwift and SwiftDate in my podFile. I'm creating my calendar with IB and I'm using the last version of JTAppleCalendar to update my project from Swift 2.2 to Swift 3.

**Comment by patchthecode** [comment]
@oskarko in that case the errors are expected. 
Many things have changed in version 7.
I have now made the library a direct UICollectionView subclass.
Therefore all the variable and function names have been renamed to match a UICollectionView. 
This was done so that every one will find the lib easier to use. If you can use a UICollectionView, then the calendar will come as 2nd nature to you.

The changes are many but are all shown in this video list.
Using that Video list, you will be able to the changes that were done, and how to fix the erros you currently -- > [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)
