### ISSUE TITLE
Swift 2.3 version

### ISSUE THREAD

**Issue by eyzuky** [patchthecode/JTAppleCalendar#386]
Is there a version that supports Swift 2? I know this was asked but I found the answers obscurred. 
I am working on a project that is 8 months old and absolutely cannot be migrated to Swift 3 due to technical issues, so any help is appreciated! I love this framework <3

**Comment by patchthecode** [comment]
The last version to support swift 2 is `5.0.1`
I left a branch for it if any one needs it.

But i must warn you, since 5.0.1, **MANY** bug fixes were done.
If you encounter a bug, I do not think i will be willing to go all the way back in that version to fix it, because it will be too much for me.

**Comment by eyzuky** [comment]
Wow, thanks for the quick reply. I am willing to fight these bugs myself if they occur for my needs..
Could you please introduce me to the line I need to add in my pod file in order to get version 5.0.1?

Thank you so much!

**Comment by patchthecode** [comment]
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => '5.0.1'
``

**Comment by patchthecode** [comment]
Keep in mind, that version 5.0.1 is not like version 7.0 ok.
7.0 is a huge change.

**Comment by eyzuky** [comment]
Its either handling version 5.0, or remaking all of the app (which is 100 MB of code).
Could you describe the sort of bugs I will encounter? Are these bugs very hard to track/notice?

**Comment by patchthecode** [comment]
Its hard to tell.
I do have [Change Logs](https://github.com/patchthecode/JTAppleCalendar/blob/master/CHANGELOG.md) that you can take a look at to see bug fixes. But bugs that are fixed after 5.0.1, does not mean that the bug is actually present in version 5.0.1

It could be bugs that were introduced after 5.0.1

Anyways, the takeaway from this is: 5.0.1 was used in production by many people with no issues.
If you encounter no bugs in your development, then your end users should not see any issues either.

**Comment by eyzuky** [comment]
Awesome. This is beautiful :) I love the approach you guys took with giving the programmer a free go with this framework appearance. Other calendars are not flexible and will not work out with any designer.

**Comment by patchthecode** [comment]
Thanks. :)
Will close this issue, if you have any other questions, then ask again.

Cheers 🍻 
Have a good one.
