### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by dfu-io** [patchthecode/JTAppleCalendar#407]
Hi!

Firstly, thank you for your excellent work.

I'm using the last version 7.0.2. I don't know if this issue it's related with some bug or simply I'm not implementing it correctly. I'm trying to set up a vertical calendar with each month between sections (simple headers). All examples I've seen implements old willDisplaySectionHeader method and I haven't found any information about current version. Anyway, if I understand your code correctly, should I to implement the method "headerViewForDateRange" in order to show it? because I'm doing it but it's never called.

There is the cell registration as viewDidLoad():
```swift
calendarView.register(
            UINib(nibName:"CalendarHeaderViewCell", bundle: nil),
            forSupplementaryViewOfKind: "UICollectionElementKindSectionHeader",
            withReuseIdentifier: "CalendarHeaderViewCell"
        )

```

And there is my implementation of the method:

```swift
func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {
        let cell = calendar.dequeueReusableJTAppleSupplementaryView(
            withReuseIdentifier: "CalendarHeaderViewCell", 
            for: indexPath
        ) as! CalendarHeaderViewCell
        cell.title.text = formatter.string(from: range.start)
        
        return cell

    }
```

Thanks again for your work!

**Comment by patchthecode** [comment]
Did you include the month size?
The old function is gone, so you can remove it and replace it with this one instead.

```swift
func calendarSizeForMonths(_ calendar: JTAppleCalendarView?) -> MonthSize? {
   return MonthSize(defaultSize: 40)
}
```

**Comment by dfu-io** [comment]
That's right.

Solved and thank you!

**Comment by Pedroalexandrelopes** [comment]
Hi,

I made the mistake of updating this library to v7.0+. After resolving all the issues and changing method signatures, the only thing that is missing now, are the headers. I tried to implement calendarSizeForMonths but when I do, the app crashes with error `"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view UICollectionElementKindSectionHeader in section 4 when there are only 0 sections in the collection view'"`

What does exactly this method return?

**Comment by patchthecode** [comment]
@Pedroalexandrelopes 

Sorry for the issues you have experienced since updating to 7.0
I'll try to make your transition easier.

version 7 has a host of issues fixed.
At this point there are only few known issues with it.
To get rid of your error, can you put this `masterBranch` in your podfile?

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

Let me know if your issue has been resolved.
MasterBranch will be released within a week or so to be version 7.0.3

**Comment by Pedroalexandrelopes** [comment]
@patchthecode 

Since I'm near the deadline to beta test, I had to go back to version 6. I'll try to update later.
Thank you

**Comment by zocario** [comment]
@patchthecode For info I had the same issue and using `master` branch solved it ;)

**Comment by patchthecode** [comment]
@zocario yea, i fix a crash issue on master branch.
I'll be releasing it this weekend.
