### ISSUE TITLE
Updating selected dates

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#41]
When my app loads it gathers all dates in a database and selects them. When a user taps on some date it should reselect all dates in real time. So if I tap i.e. on a June 1st and then June 4th, all in between should be selected. I have reference to all dates in between but how do I properly deselect all dates and select them again?

calendar.selectedDates.removeAll() won't work. It alerts me that selectDates is let.

**Comment by patchthecode** [comment]
Ok. I'm a little unclear what you're asking.
Basically you want to know how to deselect already selected dates?

If you are using the multiselect date feature, then you can deselect the selected dates by doing this.

```swift
let selectedDates = calendar.selectedDates
calendar.selectdates(selectedDates)
```

You will then be selecting the already selected dates, thereby causing them to be de-selected. Let me know if I correctly answered your question.

**Comment by antonijap** [comment]
Actually, that is a great fix. Thanks. Maybe there could be a function for resetting a Calendar so all selected dates are then, well, not selected.

**Comment by patchthecode** [comment]
Hmm. Well this wasnt really a "fix".
This is the way it has to be done.  I provided the `selectdates` dates function so that you will have the array or all your seleted dates. You the coder is now free to do with it as you please, and that includes selecting them again. Do you think i should have a dedicated function to reset dates?
