### ISSUE TITLE
Calendar changes the first day of the week on first selection

### ISSUE THREAD

**Issue by kristof4ad** [patchthecode/JTAppleCalendar#43]
Hi, 
the strange situation happen after upgrade to 4.0.0:
when I display calendar it looks like this:
![simulator screen shot 8 jun 2016 11 24 12](https://cloud.githubusercontent.com/assets/10072495/15891394/3141d9e6-2d6c-11e6-8d9e-8cdab3891d6f.png)
after you click on June 1st it changes to this
![simulator screen shot 8 jun 2016 11 24 50](https://cloud.githubusercontent.com/assets/10072495/15891422/4e14e4f0-2d6c-11e6-98ca-d409e154dd44.png)
additional clicks do not affect it.
Note that days of the week are hardcoded outside calendar view so they do not change ....

**Comment by patchthecode** [comment]
OK, can you paste me your `viewDidLoad()` code?
I need to see the code you are using to setup the calendar.

**Comment by patchthecode** [comment]
Ok. If my assumption is correct, here is your problem. (let me know if i was wrong)

Important: If you do anything that changes the `Layout` of the calendar, then you need to do a `reload()`

For instance i see that you have `Monday` as your first day of week instead of the default `Sunday`. Changing this value will change the layout of the calendar, therefore it needs to be reloaded.

So at a very basic level, your view did load should at least have this:

```swift
calendarView.delegate = self
calendarView.dataSource = self
calendarView.firstDayOfWeek = .Monday
calendarView.reloadData() // This updates your layout
```

So what happened was probably this. You forgot to call `calendarView.reloadData()`, but you did change the start of week. The calendar was then flagged as `layoutNeedsUpdating`. So on the first `reload()` that you called, it correctly updated its layout causing your view to change. So this is possibly your first error.

2nd, i do not know what code you have in your click event, but, you do not need to call calendar reloads on clicks. You generally call `reload()` for pretty much the same instances as you would call it on a `UITableView`

**Comment by patchthecode** [comment]
One other thing.. thats a interesting calendar

You have the 

s    m    t    w    t    f    s    
          Month label
CalendarView__________
|                                         |
|                                         |
|                                         |
|____________________|

Why not remove the header view. Put the s/m/t/w/t/f/s closer to the calendar view, and then have an external month label above the s/m/t/w/t/f/s ?  Was just wondering

**Comment by kristof4ad** [comment]
Hi, 
calendarView.reloadData() solved the problem!
Thank you

**Comment by kristof4ad** [comment]
Layout of calendar is inspired a bit by Airbnb
![img_1052](https://cloud.githubusercontent.com/assets/10072495/15899395/744a8824-2d93-11e6-9027-db837d496332.PNG)

**Comment by patchthecode** [comment]
Cool. gotcha.
Well glad every thing worked out. 
I'm off to fix one last bug i am seeing. I'll be getting reader for another version 4.0.1 sometime over the weekend if all goes well.
Have a good one. Closing this.
