### ISSUE TITLE
Non-strict boundaries AND headers

### ISSUE THREAD

**Issue by nameghino** [patchthecode/JTAppleCalendar#430]
Jay,

I'm trying to create a layout that requires non-strict boundaries AND headers. Is my case completely lost? Why does registering headers makes the calendar ignore the non-strict boundaries?
Using 6.1 on iOS 10.

Cheers and thanks!

**Comment by patchthecode** [comment]
Can you show me an image of what you want this calendar to look like?
I will be able to tell you if its possible or not.

**Comment by nameghino** [comment]
![img_1240_for_posting](https://cloud.githubusercontent.com/assets/143710/26501142/4057fcce-41fe-11e7-80e0-65a8c79fda2d.jpg)

I thought of "faking" a header by making the cells that contain the first week of a month a bit taller and stuffing the fake header there, but I couldn't find any delegate method that would allow me to specify a cell's size

**Comment by patchthecode** [comment]
haha wow..
ok on first glance, yours might be a lost case. Hmm. let me think.

so it seems that the "headers" only appears on the 1st of the month.

is it possible that instead of headers, you can design your cell with 
1. A 1st label at the top  - which will show the month
2. A gray colored view
3. A 2nd label lower to the bottom for the date

Now if the month = the 1st, you can set the `isHidden` property of label1 (at the top) to false. Also set the `isHidden` property of the gray view to be false.

Then get the `cellState.row` number of the 1st Date.
Save that number.
To set the visibility of the grayView of the other dates 2 & 3, do an if statement check (only for dates which are the 2nd, 3rd........ .....7th). And if those dates appear on the same row as the first, then set the `isHidden` property of the grayView to be false.

This is my first attempt guess :)

<img width="351" alt="screen shot 2017-05-26 at 10 55 46 am" src="https://cloud.githubusercontent.com/assets/2439146/26506554/e8d0453e-4201-11e7-9375-bf6ed6509524.png">

**Comment by nameghino** [comment]
Thanks a lot for your elaborate answer!

What you wrote about was my first idea, but what stopped me from doing it is that, let's say the cells are H points tall, but cells from the row that has the "header" have to be taller to account for the space in between.

Is it possible to have two different sizes for cells? I found a delegate callback that lets me specify the size of the header, but none regarding the cell size :(

**Comment by patchthecode** [comment]
i see what you mean.. hmm..
I think what is needed for you is an upgrade then.
I did not code the calendar in mind to allow headers when users have a flowing header like you have.
I wil have to think about this.

**Comment by patchthecode** [comment]
After much consideration, i do not think i will go forward with this upgrade.

The problem is that header is separating 2 different dates sections.  

<img width="806" alt="Screen Shot 2019-05-17 at 1 46 50 PM" src="https://user-images.githubusercontent.com/2439146/57946568-96b92400-78aa-11e9-97d6-f29bf49b8d0e.png">

**Comment by patchthecode** [comment]
You can create a fake header like you mentioned by designing every cell to have a space for that header.
