### ISSUE TITLE
Use of undeclared type 'JTAppleDayCellView'

### ISSUE THREAD

**Issue by Geekbell** [patchthecode/JTAppleCalendar#446]
Following Part 1 of Tutorial:

`import JTAppleCalendar
class CellView: JTAppleDayCellView {   
}`

Getting error "Use of undeclared type 'JTAppleDayCellView'

I did notice that the Tutorial is for Version 6.

**Comment by Geekbell** [comment]
Downloaded Example and noticed it's changed. Should be:

`import JTAppleCalendar

class CellView: JTAppleCell {
`
In case anyone else has the same issue.

**Comment by patchthecode** [comment]
Yea. You're correct.
I changed the name in version 7 because well.. it was too damn long to type 😂🍻

**Comment by Geekbell** [comment]
I followed the tutorial and seem to have several other issues. Is there a plan to update the documentation any time soon? It seems really useful to get a feel for this, but needs some updating.

**Comment by patchthecode** [comment]
For now all i have are the videos, They are faster to make because i just talk instead of type.
And people ask ah lot less questions because they are clearer.
Have you seen the videos yet?

Or, is there something else you wish to know? Just ask and I will compile all the questions into one document/vid.

**Comment by SerggioC** [comment]
what an awesome thing to do! renaming objects on version changes!
