### ISSUE TITLE
Getting JTAppleCell instance nil on 'didDeselectDate' call back method 

### ISSUE THREAD

**Issue by anushak89** [patchthecode/JTAppleCalendar#466]
Hello Jay, 

I'm using JTAppleCalendar version 7.0.2 (using pod 
**pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'**) on my application. Everything was working fine and it is a very well documented library too. 
![simulator screen shot jun 21 2017 3 36 00 pm](https://user-images.githubusercontent.com/8233385/27405550-94fa9aa4-5697-11e7-9587-301fd508fd4b.png)

But now I'm facing a strange issue. For some date in each month view JTAppleCell is nil on 'didDeselectDate' callback. And the strange thing is, every time it is the bottom-left corner cell (In given screenshot it is 26). If you swipe to next month you can find this same issue on  bottom-left corner cell there and on return back to the current month issue will be gone.

I tried to override 'isSelected' variable on CellView class. And I figured out one thing that, for this particular cell 'didSet' is calling two times on cell selection and second one is with a value 'false'. I don't know why it is calling.

```swift
override var isSelected: Bool {
        
        didSet {
            
            if !isSelected {
                
                // Cell Deselected
            }
        }
    }
```
Also I've logged on other callbacks. 
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell
``` 
this method is called on some date selection (top two week and last week dates mostly) and all that time `cellState.text` is same (the cell with the issue, '26' on above case).

<img width="1152" alt="screen shot 2017-06-21 at 4 10 54 pm" src="https://user-images.githubusercontent.com/8233385/27406963-461fac26-569c-11e7-84ab-031349d0e02f.png">

I'm unable to find out a solution here. Could you please take a look on this? 

Thanks,
Anusha

**Comment by patchthecode** [comment]
Hey. Thanks. I try to document it very well 👍 

First thing, let's do a `pod update` 
Your master branch should say that you are on version 7.0.5
This version has fixed some issues.

Also note that if you update to this version, and you use the `shouldSelect/shouldDeselect method, please change the method's signature to what is found here -> https://github.com/patchthecode/JTAppleCalendar/issues/438 because I have changed it.

Now to your error. In version 7.0.5 I wanted to remove the `isSelected` cell property, until one developer complained -> https://github.com/patchthecode/JTAppleCalendar/issues/436. So i decided to keep it. 

The variable that keeps knows the `isSelected` property of a cell is the `cellState` property, and **not** the `isSelected` property on the cell.

Can you try this?
pass the `cellState` property to the cell, and instead use it to determine the `isSelected` state of the cell. -> `cellState.isSelected`. And let me know if this works.

But you have raised an interesting point. Most developers expect the `isSelected` property to be on the cell itself. So i will soon put an update that fixes this.

The root cause of the problem (if i understand you issue correctly) is this ->
You have single single selection enabled (not multi-select), but still when you tap on an `outDate` you see 2 cells selected right? This code I have put is the source of the problem. Even though single selection is on, 2 cells are shown as selected -> the outDate, and its corresponding inDate. Therefore I have the `cellState` to keep track of the selections and not the `cell.isSelected`. This will be changed soon.

Let me know if the above suggestion to use `cellState` works.

**Comment by Dean151** [comment]
>Your master branch should say that you are on version 7.0.5

When I check the "release tab" of Github, I find that the last release is 7.0.4 ;
This make me no way of installing 7.0.5 using Carthage.
Is there an issue with your tag pushing ?

**Comment by patchthecode** [comment]
@Dean151 yes, latest code is always on master branch. And when it is officially released, then i create a tag for it.  I think there should be a way to use master branch with carthage right? I'm not sure of how though, as I am more used t cocoapods.

**Comment by Dean151** [comment]
@patchthecode : yes of course it's possible, and that's what I'm doing right now, but my workflow is to "freeze" the code in production, restraining a version number. I update manually, making sure everything is okay. So I can't freeze the version number on master, but don't worry, I'll wait for the tag 7.0.5 ready to be pushed :)

**Comment by patchthecode** [comment]
@Dean151 ah. i understand now. ok then, i'll see how soon i can do for this weekend.

**Comment by anushak89** [comment]
Hello Jay,

Thank you so much for your response. I've just updated pod to latest version (7.0.5). The above issue is fixed now. I didn't change anything from my end.
But now it is calling `func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters` callback on each time the calendar position changes (I'm changing calendar position on date selection and deselection) and resetting my visible month to starting month of configured period. But it's ok. I can scroll to selected date / month after position change.

Thank you!
Anusha

**Comment by patchthecode** [comment]
@anushak89 ok this should be expected.

> But now it is calling func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters callback on each time the calendar position changes (I'm changing calendar position on date selection and deselection) and resetting my visible month to starting month of configured period.

This is not good.

Can you let me know what you mean by changing the calendar position?
If you are changing the position which results in a layout change, then yes this is expected.
But
if you are changing the position by simply scrolling to a date, then I will have to fix this.

**Comment by anushak89** [comment]
@patchthecode No Jay, I'm changing the layout position (moving up the calendar view to show a footer view on date selection and moving the calendar down on date deselection). But the visible month was not reseting before and it is after the update. And as you said it is expected and no problem with that.

Thanks!

**Comment by patchthecode** [comment]
@anushak89 alright I understand now. Yes this is do to an update i did on the master branch.
ok cool. Have a good one.
Cheers 🍻

**Comment by Dean151** [comment]
@patchthecode Any idea for when you will release the final 7.0.5 ?
