### ISSUE TITLE
Calling reloadData() right after calling selectDates

### ISSUE THREAD

**Issue by iamsarathi** [patchthecode/JTAppleCalendar#476]
I have tried to reloadData inside didScroll method but this is not calling cellforrowatindex for all dates all dates

**Comment by rajhcss** [comment]
I am facing a similar issue - all cells are not reloading i.e. the cellForItemAtIndexPath is not executed for all cells.  I call reloadData(completionHandler: nil) when a date/cell is selected to update all the cells in the currently displayed month.

Depending on the date or range of dates selected, some cells are disabled based on some business rules.  I implemented selecting a date range when we were using an older version of JTAppleCalendar (version 5).  This feature used to work.  It does not work in the version we are using now (version 7.0.2).
I noticed that the issue was all cells are not reloaded, when the reloadData(completionHandler: nil) function is called.  The strange thing is, depending on the date selected, all cells are reloaded in some cases and not in other cases.

One other thing to note is that when I Traverse to the next/previous month and come back to the current month, all the cells are displaying as expected.  Thanks in advance.

**Comment by parthasarathim** [comment]
this only happens, If you do 
`calendarView.selectDates(dateToBeSelected) 
                calendarView.reloadData()`

This is because the `calendarView.selectDates` is not having completionHandler. 

This can fixed for time being
`calendarView.selectDates(dateToBeSelected) 
    DispatchQueue.main.async {
            calendarView.reloadData()
}`

**Comment by rajhcss** [comment]
Thanks, Partha.  But your solution does not work in my case.  I do not use the function "calendarView.selectDates(dateToBeSelected) ".  I instead use the didSelectDate delegate function, inside of which I call the reload.

**Comment by parthasarathim** [comment]
try doing this inside`didSelectDate`
```
DispatchQueue.main.async {
            calendarView.reloadData()
}
```

**Comment by rajhcss** [comment]
Yep, already tried that.  Does not work.  Thank you.

**Comment by rajhcss** [comment]
I think I may have found the issue in my situation.  It is, I believe, a bug.  

In the below function, not all indexPaths are reloaded.  ```public func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath)```

When I comment the code below, all cells are reloaded ```        if !pathsToReload.isEmpty {
            self.batchReloadIndexPaths(Array(pathsToReload))
        }
```

**Comment by patchthecode** [comment]
Investigated on [this thread](https://github.com/patchthecode/JTAppleCalendar/issues/537)
