### ISSUE TITLE
Release the 7.0.5 version

### ISSUE THREAD

**Issue by Dean151** [patchthecode/JTAppleCalendar#485]
Please, do :)

**Comment by patchthecode** [comment]
haha. okok.
You use carthage right?
I think when we last spoke, it had a problem to do with the version number on the podfile? (if i remember correctly..i hope)

So what i can do is bump the version number back down on master branch so that you can use it.
Will this work?
Reason for the release delay is because i was tied up with other projects. And I didnt want to release 7.0.5 without fully testing.

**Comment by Dean151** [comment]
I can also try the 7.0.4 version on my release, see if it fit my needs. I don't really know what you fixed in the 7.0.5 version.
It's just I can't release a version of my app without "fixing" the version number in it. (we manually update version number and test everything to be sure !)

Yes, I do use Carthage.

**Comment by patchthecode** [comment]
released.
if any carthage issues, let me know.
