### ISSUE TITLE
Facing difficulties of trying to add events to calendar

### ISSUE THREAD

**Issue by flavoredtaco** [patchthecode/JTAppleCalendar#490]
I am currently using the latest version of JTAppleCalendar. After following the video series, i am still having a difficult time adding events to my calendar and having it show with a red dot. I am trying to make it so that when a user clicks on a date on the calendar, it shows the event of that day in the space below the calendar. 

Any and all feedback/guidance is appreciated!!

[Progress.zip](https://github.com/patchthecode/JTAppleCalendar/files/1165964/Progress.zip)

**Comment by patchthecode** [comment]
You have the configure cell function created, but you are not calling it.
Also, you will not be able to see your dot view, because you did not have any constraints on it.
Also, on your interface builder, you have made the class of your dotView to be `eventDotView` which does not exist, therefore when you run the app you will constantly get a warning.

Here is the fixed file. Cheers 🍻 
good effort.
[Progress.zip](https://github.com/patchthecode/JTAppleCalendar/files/1166334/Progress.zip)
