### ISSUE TITLE
How to show date as selected without allowing it to be selectable?

### ISSUE THREAD

**Issue by tkirby** [patchthecode/JTAppleCalendar#547]
I have a kind of strange requirement for an app I'm working on.  If the user selects tomorrow on the calendar, they want the selection to display today and tomorrow. However today should not be able to be selected directly. Nothing I've tried seems to get me that behavior so far. I can have the data show as selected only if I allow it to be selectable.

I hope that made some kind of sense.

**Comment by patchthecode** [comment]
hmm.. i am not understanding. Is there some screenshot so that i can get a better idea?

**Comment by patchthecode** [comment]
Use the `shouldSelect` delegate function to determine if a cell should be selected or not.

You can then check if the if the selection was done programatically or by the user. You can allow it if it is a programatic selection.

programatic/user selection has been added to the master branch code.
Can you try the master branch and let me know if your issue is resolved there?
put this in your Podfile and then do a pod update

pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'

Master branch has a significant change.

    you must implement willDisplayCell. The code you put in there, is pretty much the same code you put in your cellForItemAtIndex function

**Comment by tkirby** [comment]
I actually figured it out after some messing around.

**Comment by patchthecode** [comment]
awesome.
