### ISSUE TITLE
Random scrolling to beginning

### ISSUE THREAD

**Issue by artemstepanenko** [patchthecode/JTAppleCalendar#592]
Hello guys,

I've found one more bug. Sometimes when I call `func reloadDates(_ dates: [Date])` the calendar is scrolled to the beginning. It happen rarely but very annoying.

Thanks.

**Comment by patchthecode** [comment]
Which version of the calendar are you using?

Can you use master-branch version of the library to see if your issue is already resolved?
I'll be releasing branch version in about a week or so.

replace this in your pod file to try it
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

Then do `pod update`

it will ask you to implement a `willDisplayCellFunction`. The instructions here will let you know what yo put in that function -> https://github.com/patchthecode/JTAppleCalendar/issues/553

**Comment by artemstepanenko** [comment]
Thank you very much. I'll keep you posted.

**Comment by artemstepanenko** [comment]
@patchthecode I've followed your instructions and now I have 56 compilation issues reported by my Xcode 9.0. Am I doing something wrong?

**Comment by patchthecode** [comment]
hmm.. can you join me here? -> https://gitter.im/cdunn2013_twitter

**Comment by artemstepanenko** [comment]
Texted you.

**Comment by patchthecode** [comment]
Not sure if you texted the correct address. Not seeing your message.

**Comment by patchthecode** [comment]
closing this issue.
version 7.1.0 has been released.
it seems we have very different time zones.
Update me if the latest version resolved your issues.
