### ISSUE TITLE
DaysOfWeek does not match Apple's number scheme

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#60]
Unless I'm wrong, seems Apple uses 1 for Sunday, 7 for Saturday - JTAppleCalendar is using 1 for Monday, 7 for Sunday. Can the DaysOfWeek be changed to match Apple's?

**Comment by patchthecode** [comment]
Ok, this is a small fix, i can get a patch out tomorrow. (its a much smaller fix that your enhancements. Btw i am still looking into it. It calls for a massive change)

**Comment by krisanthony** [comment]
Hey that's great. I'm using it for dynamically generating day names for the calendar header. Currently just shifting the DaysOfWeek 1 to the right to match apples.

As for the other enhancements for week view. I decided to change my design to use the full month view instead so no need to add those unless there are others interested in them.

**Comment by patchthecode** [comment]
Cool. I have made the change already.  I will push it to the master branch at the end of today. If you wish to use it right away, you can modify your pod file to use the latest version on master branch, instead of a specific 4.1.x number. I'll do an official release after I add some more stuff.

And in regards to the week view, i will add it. If one user needed it, then chances are other users need it as well.

Its just that I want the version to become more stable before i put in anymore enhancements.
Coming down the pipe are: 
(1) Range selection 
(2) Date limiting  - (because currently it just does the whole month)

**Comment by patchthecode** [comment]
Updated. Pushed to master branch. Release coming soon.
