### ISSUE TITLE
handleCellSelected() not working sometimes after scroll to segment

### ISSUE THREAD

**Issue by REAOrlando** [patchthecode/JTAppleCalendar#620]
Hi JT,

I'm using version 7.1.3. I'm really happy with this library and have a small issue that I hope you can help with.  I created some buttons and functions to scroll ahead or back to the next segment by either year or month.  This feature works perfectly when stepping in one direction for any number of clicks, but if you click the opposite direction, the calendar does scroll to the correct segment, it does select the correct date, but it does not add the selectedView colors.  The weird part is that if you keep stepping in the opposite direction it will eventually start adding the selected view color again.  I'm at a loss and hope you can take a look at the code.  I created a single view project for you to replicate the issue.  

https://github.com/REAOrlando/JTAppleCalendarTest

![giphy-2](https://user-images.githubusercontent.com/24299944/32806121-80e9a28c-c959-11e7-99b2-fadc35ac73e3.gif)

**Comment by patchthecode** [comment]
checking this now.

**Comment by patchthecode** [comment]
Problem is in your handle code.
You have this:

```swift
guard let validCell = view as? CustomCell else { return }
```

the cell is nil at this point and so it exits your funciton.

**Comment by patchthecode** [comment]
root cause lies here
```swift
    @IBAction func minusMonthBtn(_ sender: UIButton) {
        let next = userCalendar.date(byAdding: .month, value: -1, to: calendarView.selectedDates[0])!
        calendarView.scrollToDate(next, animateScroll: false)
        calendarView.selectDates([next], triggerSelectionDelegate: true)
    }
    
    @IBAction func plusMonthBtn(_ sender: UIButton) {
        let next = userCalendar.date(byAdding: .month, value: 1, to: calendarView.selectedDates[0])!
        calendarView.selectDates([next], triggerSelectionDelegate: true)
        calendarView.scrollToDate(next, animateScroll: false)
    }
```

For example:
`calendarView.scrollToDate(next, animateScroll: false)`

The calendar may not yet finished scrolling to the date. It may be in the process of getting to the date and there for the date is not yet visible on the screen.
Therefore when you call this -> `calendarView.selectDates([next], triggerSelectionDelegate: true)`
It is possible that the selection finishes first (while the calendar is still scrolling to the date).

therefore cell will = nil -> therefore, your `guard let validCell = view as? CustomCell else { return }` will return because the cell is still nil.

You have two options for a fix
1. change your handle code
2. use a closure to make sure selection is done *after* scrolling is complete

```
calendarView.scrollToDate(date) {
    self.calendarView.selectDate.....   // This happens on completion
}
```

**Comment by REAOrlando** [comment]
Perfect! The closure does the trick.  Thank you again.
