### ISSUE TITLE
Cell customization bug 

### ISSUE THREAD

**Issue by LetSwiftDev** [patchthecode/JTAppleCalendar#634]
When I want to customize some cell my cells mixing how can I fix  it, my example project under below.
https://github.com/LetSwiftDev/CalendarBug

Also my question is
https://stackoverflow.com/questions/47485263/jtapplecalendar-custom-cell-bug-on-cellforitemat-date-in-swift-3-2

Also you can see bug in action 
https://github.com/LetSwiftDev/CalendarBug/blob/master/calendarbug.gif

How can I fix it ?

My Version number  7.1.4

**Comment by patchthecode** [comment]
One thing i noticed is that you are not using Cocoapods or Carthage. Although this is not a problem, 
i do not see the library forcing you to implement the `willDisplayCell` function like it normally would if you used carthage/cocoapods.

You need to implement that function -> #553

**Comment by patchthecode** [comment]
So i had another look at your code.
I think the error is in your code logic.

In your GIF file, you can see that: -> your date label is always correct.

Since that your date label is always correct, we know that this is not a calendar bug.
`JTAppleCell` is literally an empty cell. I do not manipulate it in any way. The only person that does the manipulation of that cell is the coder.

I tried to follow you loop code, but it was too complex for me to follow.

**Comment by LetSwiftDev** [comment]
When I adding that code gives me

`Extra argument 'date' in call`

**Comment by patchthecode** [comment]
You need to paste to me the code that you did. Else i will not know.
here's what, chatting here is too slow.
join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by LetSwiftDev** [comment]
Doesn't work ! This is bug look at question, someone added answer with your willDisplayCell codes but doesn't work.. 

You can see and test !

https://stackoverflow.com/questions/47485263/jtapplecalendar-custom-cell-bug-on-cellforitemat-date-in-swift-3-2

**Comment by patchthecode** [comment]
closing as issue is resolved on stack overflow.
