### ISSUE TITLE
Resize Calendar View without redrawing/resetting/reloading data.

### ISSUE THREAD

**Issue by cschraga** [patchthecode/JTAppleCalendar#640]
I'm the same project as previously closed issue [627](https://github.com/patchthecode/JTAppleCalendar/issues/637).

Is there a way I can resize the calendarView, without changing the size of any of the underlying collection view cells, without the entire calendarView redrawing and resetting?

I have my calendar view in a split view next to a task list and from time to time the user will want to shrink or collapse the task list to get a better view of the calendar.  It will be more user friendly if I can "freeze" the calendar view in place during resize operation.  Make sense?

**Comment by patchthecode** [comment]
Ok, will check it out some more over the weekend.
I got a busy recently.

**Comment by patchthecode** [comment]
ok finally have a chance to get a good look at the question.
so when you shrink the calendar's frame, I understand that you do not want the calendar's cells to resize.

So can you explain how do you want the calendar to respond?
When the calendar's frame shrinks, you want the cells width/height to stay the same? This is the part i am unclear on.

**Comment by cschraga** [comment]
I'll show screen shots it might be easier.

So I have the JTAppleCalendar in a container view, and I use it to schedule assignments for an education app by dragging and dropping from a tableview.  Problem is that when i resize the container view it always redraws the calendar which is an imperfect experience.

All I want to do is NOT redraw the calendar when i resize the container view.  This would be possible in a regular collection view as long as the contentSize is larger than the screen size.  I'm guessing it might have something to do with ViewWillLayoutSubviews being called on the superview resize but I'm not 100% sure. Make sense?

**Before resize:**
_(Content Offset 600px / One month)_

![q2a](https://user-images.githubusercontent.com/15016969/33558957-52e9a4ce-d8d9-11e7-85a1-c08c6605189f.png)



**After resize:**
_(Content Offset 0px) but should be 600px_

Calendar redrew and scrolled up to contentOffset = 0 when I want it to stay at 600px

![q2b](https://user-images.githubusercontent.com/15016969/33559008-767d21a4-d8d9-11e7-83f3-0ffcf2519316.png)

**Comment by patchthecode** [comment]
hmm. a long time ago, i propably thought about this feature.

`calendarView.allowsDateCellStretching = false`

but since no one asked for it, I do not think i finished implementing it.
I can take a look to try. But this wont be completed soon as I am on other projects for a short while.

What you can do as a workaround is something like what this guy did with his JTAppleCalendar -> https://github.com/patchthecode/WLAppleCalendar

In his gif image you can see the calendar "resizing" and the cells are not redrawn.
How did he do it?

The bottom tableView is Above the calendar view. It has a NSLayoutConstraint set to the top of the viewController. Then he adjusts the size of that constraint to hide bottom portions of the calendar when needed. Can this technique word for you?

Its because of techniques like these that i think `calendarView.allowsDateCellStretching = false` might be unneeded. Let me know if this works for you.

**Comment by cschraga** [comment]
Ill try that. Itll take some hit test rejiggering but it might work. I'll let you know how it turns out.

**Comment by patchthecode** [comment]
awesome. cool

**Comment by cschraga** [comment]
it worked. Just had to rejigger some hit tests and constraints. Thanks.
