### ISSUE TITLE
Wrong Week day

### ISSUE THREAD

**Issue by dastanbb** [patchthecode/JTAppleCalendar#646]
Hi!
I'm using latest version and latest example app to recreate a problem. Please download example app and set next settings an in image below. You might notice that current date (December 4 2017 is in wrong place depending on week day). It should be placed below Monday. Please help. 
![simulator screen shot - iphone 8 - 2017-12-04 at 08 47 42](https://user-images.githubusercontent.com/32884227/33564836-5e196720-d8d0-11e7-8727-75e41738b86c.png)

**Comment by patchthecode** [comment]
setting it to off means it will not be generated. In which case you will need to change the label for the header because the header you see in the example app was manually created by my self (it is not managed by the library).

It looks like you DO want the dates to be generated, but you just want them to be invisible. In which case you click on this button -> 

<img width="635" alt="screen shot 2017-12-04 at 8 58 09 am" src="https://user-images.githubusercontent.com/2439146/33565212-57cf2d86-d8d1-11e7-8f1e-2225b9fcceab.png">

With this library you can design any grid style standard calendar. A better idea would be to show me  a picture of the calendar you are trying to build and i will tell you the configuration.

**Comment by patchthecode** [comment]
Also, the video list will help you greatly -> [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

**Comment by dastanbb** [comment]
Thank you for the quick response! I want to implement one-row calendar to scroll horizontally week by week (paging collection view). So we have 7 weekday labels on top and navigate a user to current date. Hope this is clear.

**Comment by patchthecode** [comment]
Does this help ->  https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by dastanbb** [comment]
Yeah, It did. I was using incorrect **generateInDates**. Thank you, man! I really apreciate your work!

**Comment by patchthecode** [comment]
cool. 🍻
