### ISSUE TITLE
How to add recurring Events?

### ISSUE THREAD

**Issue by pradeepispv** [patchthecode/JTAppleCalendar#652]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
I dont know what you mean by recurring events.
But if you want to add events, you can follow the example on this video -> https://www.youtube.com/watch?v=CQNotydm58s

**Comment by pradeepispv** [comment]
I was asking for a event to be added for all the years at one shot.With out any lag in the performance.

Lets take birthday ,it will be a event for every year.If i give dd-mm i want it to add for all the years.

Recurring events is general term in apple calendar.

**Comment by patchthecode** [comment]
OK. This calendar does not have an events feature built-in. I left it out so that the developer can have more control over it. All this library provides is a template for the developer to create any calendar design he wants (so long as it is a standard calendar).

Things like animation, events etc do not exist on this library. By leaving these things out, it makes this calendar 100% flexible. Similar to Apple's components like their UITableView or UICollectionView, they do not create any predefined things like this; they leave it up to the developer. Therefore i followed this pattern.

However, even though it does not come with these things built-in, if you look at the videos, or look and all the images, you can see that many developers have done things what you are asking; because this library makes it easy to implement.

In terms of your "all the years at one shot.With out any lag in the performance" question though, I do not think Apple calendar does this. No coder would add all years in one shot. Under the hood, the Apple Calendar will only load the years that are **visible** to the user which will give you the impression that every thing is loaded in one shot. But it is not.
