### ISSUE TITLE
How to display the event dots on the calendar by using my data in the Firebase?

### ISSUE THREAD

**Issue by dingckc** [patchthecode/JTAppleCalendar#656]
Hello, thank you for this fantastic calendar. 
I'm now using version 7.1.4 and I'm a newbie of the Swift.

I've followed the tutorial you provided on YouTube to build my own. And, I created a Firebase to store the dates and events which are created by users. 

In the tutorial, I saw that the data were inserted by hardcode.
![image](https://user-images.githubusercontent.com/34504255/33929294-f000d006-e023-11e7-9a36-3ac60d5548af.png)

But, may I know how to display the event dots on the calendar by using my data in the Firebase?  

Here is the function of the "loading data form Firebase" in my project. 
![image](https://user-images.githubusercontent.com/34504255/33929980-59226156-e026-11e7-961c-e12f92bfe77e.png)

One more question, how to show more than 1 event on the same date? (like the following calendar)
![image](https://user-images.githubusercontent.com/34504255/33929535-ca0ce6c2-e024-11e7-9a35-4b8c8251c5b0.png)

Thank you very much!

**Comment by patchthecode** [comment]
> In the tutorial, I saw that the data were inserted by hardcode.

In the video, i entered the information hardcoded to "simulate" my database. The reason why I did that is becase it gives you a simple example for how to do it for your databases. I did not show a real data base example becase you develpoers will need to know this yourself. For you, your database might be firebase, or another developer, its a custom server, and for another, its MySQL, SQlite, CoreData etc etc etc. Since there are too many i just showed a generalized example. Personally, i have never used firebase, so i cannot help you there much.
I see you have `self.posts.append(post)`, so my guess is that you need to conver that post into a format that you can feed to the library just like i did in the example.

> One more question, how to show more than 1 event on the same date? (like the following calendar)
Again, this question is different to each developer annd is not related to the calendar.
Think of the question as this. How can you developer an app with a grid of buttons and a table below it, so that when you tap on a button, the table below it displays a list of strings that were assigned to the button? There are many ways to do this. If you can answer that question, then you can do the same to the library. These codes are developer specific and not related to the library.

I hope these answers were helpful to guide you int he right direction.
