### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by Prashanna7** [patchthecode/JTAppleCalendar#734]
I am using the latest version i.e JTAppleCalendar 7.1.5 and i did all the things that are told to do in tutorial and i also saw the latest update in code and i updated mine as well, but when ever i launch my app it gets crashed and says the error mentioned in title.
![screen shot 2018-03-06 at 11 51 11 am](https://user-images.githubusercontent.com/19919770/37016618-41cb16d8-2135-11e8-8dbd-2c61173c5209.png)
my code :

      import UIKit
      import JTAppleCalendar

    class CalendarViewController: UIViewController {
    
    let formatter = DateFormatter()

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }

       }

      extension CalendarViewController : JTAppleCalendarViewDelegate,                                                                   JTAppleCalendarViewDataSource{
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2017 01 01")
        let endDate = formatter.date(from: "2017 12 01")
        
        let parameters  = ConfigurationParameters(startDate: startDate!, endDate: endDate!)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell  = cell as! CustomCell
        cell.labelData.text = cellState.text
        
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.labelData.text = cellState.text
        return cell
       }
 
    
    
        }

**Comment by patchthecode** [comment]
hey can you zip your sample app and send to patchthecode@gmail.com ?

**Comment by Prashanna7** [comment]
check your mail

**Comment by patchthecode** [comment]
This is because you have 2 JTAppleCalendars on your storyBoard.
You have correctly setup one, and the other is incorrect (which causes the crash).

I believe you made a mistake with the incorrect one:

<img width="280" alt="screen shot 2018-03-07 at 8 18 23 am" src="https://user-images.githubusercontent.com/2439146/37103874-255eb24c-21e0-11e8-80e3-d655ac4cd32a.png">

On yoru story board, click on this. Why did you set this to be a `JTAppleCalendarView` ?
This a is a regular `UIView`

The one that needs to be set as the `JTAppleCalendarView` is this one 

<img width="266" alt="screen shot 2018-03-07 at 8 19 48 am" src="https://user-images.githubusercontent.com/2439146/37103964-54333480-21e0-11e8-8fa3-a8309811f965.png">
