### ISSUE TITLE
Ways to make month label update in real time

### ISSUE THREAD

**Issue by FishForLife** [patchthecode/JTAppleCalendar#744]
Firstly, thank you for this amazing library!

I would like to ask if the month label can be updated in real time as the user scroll very quickly. 
I was updating the month label in didScrollToDateSegmentWith but then the month will only update when the animation stops.
Is there a way to update it when the the scroll will go to a month ? (e.g. willScrollToDateSegmentWith in delegate) 

Thanks!

**Comment by patchthecode** [comment]
Sorry for the extremely late reply, but we do not have a willScrollToDateSegmentWith function.

But since this library is a UICollectionView >> UIScrollView, you have access to the `scrolViewDidScroll functions` and also the `willEndDragging` function.

I do not have a built in way to do this right now, but i will in the future.
In the mean time you'd have to go the hard way and calculate it your self.

**Comment by patchthecode** [comment]
closing as this is a duplicate for this -> https://github.com/patchthecode/JTAppleCalendar/issues/706
