### ISSUE TITLE
Using JTAppleCalendar in ObjetiveC

### ISSUE THREAD

**Issue by elr0nd** [patchthecode/JTAppleCalendar#77]
Hi, thanks for this wonderful library, it seems to be the one for my development.

The thing is that I want to import in my ObjetiveC project, but once I have import the autogenerated header, I can not set the delegate and the DataSource for JTAppleCalendarView variable, the protocols are not visible, or that is what I think...

Is it possible to use this library in ObjetiveC? Do you have any example using it in a objetiveC project?

Thank you!!!

**Comment by patchthecode** [comment]
There are some users who tried porting this to objc.  They have said that it is a pain, but it does  work. Now as for me giving an example, I did not have any plans to make this a objc library for two reasons.

1. Swift is the way forward. 
2. This is just my little spare time project. I do not have enough time. (this is he main reason)

Sorry I can't be of more help on this.

One thing though, I'm not sure why you are not able to see the swift protocol. Since I'm not sure what exactly what problem you are facing, this is what i came up with. -> http://stackoverflow.com/questions/25266137/swift-protocol-in-objective-c-class
