### ISSUE TITLE
Range selection is happening different cells

### ISSUE THREAD

**Issue by yasheedv** [patchthecode/JTAppleCalendar#770]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

*. Using the latest version.

First of all Thanks for creating an amazing library.
I want to create a calendar like the below screenshot
<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406133-33db15c8-4ba1-11e8-99a2-a7264ebf62c3.png">

You can find my source code is here: https://github.com/yasheedv/JTAppleCalendarDemo
I created a range selection. But Im getting the following issues. Please help me to find a solution for this.

1. I selected April 30 to May 2 and getting the following 

<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406094-9b3b51b6-4ba0-11e8-89ce-babcdee571fd.png">

2. Selected May-5 to May 31

<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406154-5972c308-4ba1-11e8-93ec-7a40ad457333.png">

3. June 14 to July 1
<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406169-83cecb92-4ba1-11e8-8011-8c759f117ff6.png">

**Comment by patchthecode** [comment]
will take a look

**Comment by yasheedv** [comment]
Hii.. Any updates ?

**Comment by patchthecode** [comment]
ok. i only now had a chance to look at this. Sorry for the late response.

1. I selected April 30 to May 2 and getting the following 
You have shown me the image of what you have. But can you show me what you **want** it to look like?

<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406094-9b3b51b6-4ba0-11e8-89ce-babcdee571fd.png">

Keep in mind, that showing me the wrong image, does not make me understand what should be the right image. Many developers have different designs in mind.

2. Selected May-5 to May 31
Same thing here. What should it look like? I see in the image that your indates for the month of June is selected. Should it be invisible? visible?

<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406154-5972c308-4ba1-11e8-93ec-7a40ad457333.png">

3. June 14 to July 1
This is the only image that seems obvious to me that there is an error. Because i assume you do not want two end selections.  But can you help me understand for # 1 and # 2?

<img width="377" alt="screen shot 2018-04-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/34914714/39406169-83cecb92-4ba1-11e8-8011-8c759f117ff6.png">

**Comment by patchthecode** [comment]
Ive finally got around to this.
Your code was too complex for me to go through, so i created a range selection example for you.
Download the github project and run the attached sample project.
On the fourth option, you will see rangeSelection example.

**Comment by patchthecode** [comment]
will close this issue.
Let me know if youre still experiencing problems.

**Comment by IanHoar** [comment]
Just to follow up on this in case anyone else is experiencing this issue.  In example 1 and 2, it seems like the OP was trying to not show the range indication on dates outside of the valid calendar days in a month.  To achieve this you can simply check `cellState.dateBelongsTo == .thisMonth` when configuring your cells.
