### ISSUE TITLE
Is there anyway to get previous and the next month of the current month

### ISSUE THREAD

**Issue by WolfgangTorres** [patchthecode/JTAppleCalendar#783]
Great library man

Im using the version 7.1.5

I want to display the previous month and next month of the current month, Is there a function or any other way to do that??

Im currently displaying the previous and next month using
```
        let previous = visibleDates.indates.first?.date
        formatter.dateFormat = "MMMM"
        previousMonthBtn.setTitle(formatter.string(from: previous!), for: .normal)
```
```
        let next = visibleDates.outdates.first?.date
        formatter.dateFormat = "MMMM"
        nextMonthBtn.setTitle(formatter.string(from: next!), for: .normal)
```

But if there is no indates or outdates it does not work
Is there anyway i can get this months differently?

**Comment by patchthecode** [comment]
instead of using `inDates`/`outDates`, just use `monthDates`.
Then just calculate the next month of that date.
There are many examples on how to calculate it:
example --> [Here](https://stackoverflow.com/questions/39804669/how-to-get-previous-and-next-month-in-calendar)

Will close this issue, but let me know if youre still stuck
