### ISSUE TITLE
Get array of months to link to dropdown menu

### ISSUE THREAD

**Issue by EleshKliesen** [patchthecode/JTAppleCalendar#791]
On Version 7.1.5:

Hi, I'm trying to get a array of months to populate my dropdown. The dropdown simply displays a list of months and when selected scrolls the view to the corresponding month. Is there a function or variable to get an array of months as string/date/month from the calendar?

P.S Currently working around it by creating the Date array myself with the same startDate and endDate as the calendar's ConfigurationParameters, so its totally not urgent

**Comment by patchthecode** [comment]
This feature is not present.
The idea was as you just stated.

This library is just a simple UICollectionView under the hood; so the data is managed by the developer.  There is month data stored on the library, but it is not in a format you would like 😅. 

I could create a new feature to return that data to you in a good looking format, but it would be more efficient if done from your end since you know the data you provided to the library.

**Comment by EleshKliesen** [comment]
Seems fair
Thanks for the quick response!

**Comment by patchthecode** [comment]
cool. 🍻
