### ISSUE TITLE
is there any possibility  with that library to set default calendar start and end i.e i don't want any limitations 

### ISSUE THREAD

**Issue by PramodShukla10** [patchthecode/JTAppleCalendar#809]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
What is default start and end?
Do you mean you want it to forever scroll?

If so, then no. I think having one's calendar scroll 20 years back and 20 years forward is good enough. Your app wont be around long enough to matter at that point.

But if you erally do want forever scrolling, yo can update the start/end date once user gets close to the end. You'll have to manage this your self though, because this library is built to have a fixed start anda fixed end.

**Comment by patchthecode** [comment]
closing until user responds.
