### ISSUE TITLE
Spacing between Alternate cell items in single row calender.

### ISSUE THREAD

**Issue by tripathishivam35** [patchthecode/JTAppleCalendar#815]
Version Using : 7.1.5
![screen shot 2018-06-25 at 3 12 47 pm](https://user-images.githubusercontent.com/13601158/41843119-4baeab72-788a-11e8-8841-ed82b3de4228.png)

I had Implemented single row calendar using this -[https://github.com/patchthecode/JTAppleCalendar/issues/581](url)

Inside of this some space is appearing between cell items. I already added this -
```
self.collectionViewDate.minimumLineSpacing = 0
self.collectionViewDate.minimumInteritemSpacing = 0

```
In storyboard there is no space/trailing/leading constraint , all is set to 0.
Note: I can't define the background color to collectionView. This is due to some UI Requirement for highlighting selected item.

**Comment by patchthecode** [comment]
I do not know what your design should look like.
So, showing me that image does not help me much.

You need to show me the errored image, and then show me what the correct image should look like. Only then i can tell the difference. The image you posted looks ok to me :/

**Comment by tripathishivam35** [comment]
@patchthecode  **Issue I am facing is only this that There is white space of  between cell items.**
In My code or storyboard There is no space kept between cell items and i kept these to zero.Even then this white space is appearing between cells.How to remove this space in order to maintain uniform color?

```
self.collectionViewDate.minimumLineSpacing = 0
self.collectionViewDate.minimumInteritemSpacing = 0
```
Note:
I added the point of Design only because i can't change the background color of Whole CollectionView, otherwise i will be able to solve the problem.

**Comment by patchthecode** [comment]
I still do not know what white space you mean.
Do you mean this? 

<img width="457" alt="screen shot 2018-06-26 at 12 52 05 pm" src="https://user-images.githubusercontent.com/2439146/41935874-25a85a98-7940-11e8-8d31-7eaff1a0a524.png">

If this is what youre referring then this is not a library problem. It is a problem with UICollectionView.
There are many questions of stack overflow about it.

The solution in short is this.
The white line appears because your calendar Cell with is not perfectly divisible by 7.
its probably 23.34934.............etc  or something. Therefore white line appears.

So fix, simply make your calendar be a width X such that X / 7 = A
Where A is not 23.34934.............etc
A should be something like 23.34   without the recurring decimal points.

**Comment by tripathishivam35** [comment]
@patchthecode 
Thanks Man, I mean the same.
Thanks for pointing out, I was not aware about this thing.
