### ISSUE TITLE
dateBelongsTo is always set to .thisMonth after setting hasStrictBoundaries to false

### ISSUE THREAD

**Issue by ahmed-khalil** [patchthecode/JTAppleCalendar#818]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. -> 7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 -> YES
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.

In order to have a smooth date range selection, I removed the section headers and set the hasStrictBoundaries to false. However, after doing this the cellState.dateBelongsTo is always set to .thisMonth, which is preventing me from setting different colors for the date cells in the calendar based whether they are in the same visible month or not

This is my calendar configuration:

return ConfigurationParameters(
            startDate: startDate,
            endDate: startDate.date(byAddingDays: 360),
            numberOfRows: 6,
            calendar: .current,
            generateInDates: .forFirstMonthOnly,
            generateOutDates: .off,
            firstDayOfWeek: .monday,
            hasStrictBoundaries: false
        )

and the calendar is set to only show one month on vertical scroll.

In addition to, when selecting a range of dates last day in the month is highlighted as .right. After performing a couple of range selections, it would go back again to be a middle selection. Please check the attached screenshots.

<img width="374" alt="screen shot 2018-06-26 at 18 43 17" src="https://user-images.githubusercontent.com/3832428/41927027-40e085fc-7971-11e8-89bb-cd259d0358d6.png">

<img width="377" alt="screen shot 2018-06-26 at 18 43 36" src="https://user-images.githubusercontent.com/3832428/41927032-4598d73e-7971-11e8-8929-8c1271014be7.png">

Would appreciate some help :)

Thanks..

**Comment by patchthecode** [comment]
1. for range selection
```swift
calendarView.allowsMultipleSelection = true
calendarView.isRangeSelectionUsed = true
```

Also another things is needed, can you paste me both your `cellForItem` function and your `willDisplayCell` function?

2. 
> However, after doing this the cellState.dateBelongsTo is always set to .thisMonth

This is expected. `dateBelongsTo` lets the developer know which month the date belongs to. Since you removed `outDates` and `inDates` (except for the first month) then all other dates visible will belong to the `.thisMonth`.

> which is preventing me from setting different colors for the date cells in the calendar based whether they are in the same visible month or not

Can you be a little clearer on the criteria for coloring the date cells? sample screenshot maybe?

**Comment by ahmed-khalil** [comment]
The cellForItem:

`if let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarDayCell", for: indexPath) as? CalendarDayCell {
            
            cell.set(cellState: cellState)

            cell.layoutIfNeeded()
            
            return cell
        }
        
        return JTAppleCell()`

The willDisplayCell:
`self.set(cell: cell, cellState: cellState)
        
        cell.layoutIfNeeded()`

set(cell: cell, cellState: cellState) send the cellState to the cell itself so it can determine the case if selected, if date belongs to thisMonth or any other attributes that needs to be set for the cell.

What I mean by:

> which is preventing me from setting different colors for the date cells in the calendar based whether they are in the same visible month or not

I need cells that have the date of the current visible month to be colored as black for example and the other dates belonging to previous or next month to be colored with light gray.

**Comment by patchthecode** [comment]
FIY [Old version 6.0 documentation for range selection here](https://patchthecode.github.io/RangeSelection/)

**Comment by patchthecode** [comment]
closing until user responds.

**Comment by jhildensperger** [comment]
I think I'm having the same issues with a similar setup. What I want is a calendar with in dates for the first month and no out dates so the cells layout without gaps between the months.

When `hasStrictBoundaries` is true the selection works as desired, but there are gaps in the layout  between the months. When `hasStrictBoundaries` is false the dates have no gaps and if the start of the range is last day of the month the selection works as desired. The issue occurs if the start of the range is not the last day of the month or the range spans multiple months. In those cases the last days of the months have a selected range position of `.right` instead of `.middle`. Is this result achievable? 

Here is my configuration:
```swift
        let startDate = Date()
        let endDate = Date(timeIntervalSinceNow: 60 * 60 * 24 * 365)
        
        return ConfigurationParameters(startDate: startDate,
                                       endDate: endDate,
                                       numberOfRows: 6,
                                       calendar: Calendar.current,
                                       generateInDates: .forFirstMonthOnly,
                                       generateOutDates: .off,
                                       firstDayOfWeek: .sunday,
                                       hasStrictBoundaries: false)
```

`hasStrictBoundaries` true
![simulator screen shot - iphone xs max - 2018-11-19 at 22 59 50](https://user-images.githubusercontent.com/685326/48738453-5ce7c780-ec51-11e8-8b02-3cd2a12ba01d.png)

`hasStrictBoundaries` false
![simulator screen shot - iphone xs max - 2018-11-19 at 23 00 13](https://user-images.githubusercontent.com/685326/48738443-56595000-ec51-11e8-97f0-365b35a0d018.png)

Desired behavior:
![simulator screen shot - iphone xs max - 2018-11-19 at 23 07 27](https://user-images.githubusercontent.com/685326/48738414-3aee4500-ec51-11e8-9573-1c03e0a73847.png)

**Comment by jhildensperger** [comment]
It turns out reloading the dates immediately after setting them achieves the desired result. I'll do that until a fix is introduced. Also, I'm using `pod 'JTAppleCalendar', '~> 7.1.6'`

```swift
calendar.selectDates(from: startDate, to: date, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
calendar.reloadDates(calendar.selectedDates)
```

![simulator screen shot - iphone xs max - 2018-11-20 at 20 49 43](https://user-images.githubusercontent.com/685326/48799010-5d8e6580-ed06-11e8-8fa9-466c29c52c40.png)

**Comment by patchthecode** [comment]
it should work without reloading.

1. did you set **allowsMultipleSelection = true**
2. did you set **isRangeSelectionUsed = true**
3. if possible can you send me an very simple sample app that demonstrates this problem?

**Comment by jhildensperger** [comment]
Yes, I have 

```swift
        calendar.allowsMultipleSelection = true
        calendar.isRangeSelectionUsed = true
```

I'll make a simple example and share it.

**Comment by jhildensperger** [comment]
Here's what I'm doing https://github.com/jhildensperger/JTCalendarExample

Thanks for looking into it.
