### ISSUE TITLE
How to show multiple selected dates in different colour for different-different type event

### ISSUE THREAD

**Issue by PramodShukla10** [patchthecode/JTAppleCalendar#867]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
The same way you would show multiple selected cells in different colour for different data types in a UICollectionView or UITableView

**Comment by PramodShukla10** [comment]
Okay.
Thanks:)

**Comment by patchthecode** [comment]
You can find information on how to do things like this via google.
I will be able to answer any specific questions related to this library, but if the question is a general question about swift programming, I cannot do this. This takes too much times for me to check because i am swamped with questions.
