### ISSUE TITLE
How to show week calendar rows from top?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#874]
1. I am using the latest branch.
2. pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

Here's the problem. In my app, I have requirements of displaying week/full calendar as per some UI needs. So the problem, I am facing is whenever I want to show the Week Calendar it displays as a week but it's showing me at the center of the CalendarView. Is there any way (other than reducing the height of the CalendarView) to display it at the top?

**Comment by patchthecode** [comment]
Well, there is.. but it is experimental.
I never developed on it further because no one asked for it.
But just set
```swift
calendarView.allowsDateCellStretching = false
```
And let me know if that works for you.

**Comment by hemangshah** [comment]
This is not working @patchthecode. It is generating weird result.

**Comment by patchthecode** [comment]
I am not sure where my head space was when you opened this issue.

The reason why you are seeing the calendar numbers in the middle, is because the your week calendar has a large height. Therefore, it will auto center the dates in the center.

What you should do is decrease the height of the calendar for week view, and then increase the height of the calendar for the full view.

This is related to your question here which i have yet to give an example --> https://github.com/patchthecode/JTAppleCalendar/issues/913

Closing this issue.
I have a bit more time now, so i will create an example soon.
