### ISSUE TITLE
How to make sure that a month is changed in JTAppleCalendar?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#876]
1. I am using the latest branch.
2. pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

I am aware that there's a delegate method which will call whenever we make some scroll. But this is not enough to tell that a month is changed. So how to know this using in-built API?

**Comment by hemangshah** [comment]
```
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {

}
```

Right now, I am using this delegate method but it will always invokes even if I slightly scrolls. I will try with that new delegate today and let you know.

**Comment by hemangshah** [comment]
`func calendar(_ calendar: JTAppleCalendarView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo) {}`

For me this delegate is there, but it's not getting called. Anything to set?

**Comment by hemangshah** [comment]
Ok, so now it's calling, I wasn't on the master branch. Now, I am on a master branch and I have this delegate (in your code) and it gets called every time, but this isn't the solution to my question. Because, what I am looking for is a delegate should only get called if a month is changed. 

```
    func calendar(_ calendar: JTAppleCalendarView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo) {}
    
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {}
```

These guys called every time. Even if the month isn't changed.

**Comment by patchthecode** [comment]
Ok. So now i understand want you want.
You just want to know when a month has changed.

The thing is, this is know know by the developer (you) not the library. The reason why I cannot know when a month has changed is because you devs can configure this lib in too many ways.

Here is a simple case
<img width=400 src="https://cloud.githubusercontent.com/assets/2439146/19060730/6ab850bc-899f-11e6-84ad-221839041371.gif">

With a calendar like this, multiple months are displayed on the screen at the same time. 
With a setup like this, there is no way for me to tell what the developer considers _the month on the screen_.

So the way i handle it is: Whenever a scroll happens, in those delegate functions above, you get a bunch of `inDates`, `monthDates` and `outDates`. You can run a check of the the dates to see if the month has changed. You could run a check to see if the dates contain some date in the middle of the next month. This is the beast way i currently have of determining if the month has changed. (unless a developer can suggest me a better way).

**Comment by patchthecode** [comment]
maybe if you tell me what youre trying to do, then i can suggest something?

**Comment by hemangshah** [comment]
I want to call the API whenever the month is change. Right now, even if it's not change it will call the API. I am performing few other tasks when the month will get change. That, all logic is written in this delegate,

```
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {

}

```
But this will call even if I change the height of the calendar or just slide scroll.

**Comment by hemangshah** [comment]
Hi @vishnude , as @patchthecode explained currently because of there can be multiple way that one can create a calendar for their apps it's not possible for him to give us a way to check whether it's scrolled or not. So for my case, I have find an alternative which will make sure whether we have a new date? If it's a new date, I will be do the things which I want. Like wise. Hope this may help, however, I am believing that if @patchthecode will provide a solution to us it will be more help than patching our code to accomplish particular tasks.

**Comment by patchthecode** [comment]
finally got around to reviewing this.

> I am believing that if @patchthecode will provide a solution to us it will be more help than patching our code to accomplish particular tasks.

I do not believe this is patching. Me developing a solution for one developer, will not work for another developer. Because there are many different ways that a developer can define a "Month", then if i developer a solution that a "month" is changed, then i would only be developing a solution for one developer and not the other.

The best way to determine if month has changed (i think) would be to monitor **distance scrolled**.
Since you know the size of your month might be X, then you know that if the contentOffset of the calendar changed by more than X, it will be a new month.

I assume you have your calendar's scrolling mode to be either
```swift
.stopAtEachFrame
.stopAtEachSection
```

Therefore, in the following function put this.
```swift
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
  // if my calendar's content offset is > than X {
  //   run my API's because the month is changed
  // } else {
  //   do nothing
  // }
}
```

I think this is the best solution.
Will close this issue now. But let me know your thoughts.
