### ISSUE TITLE
part of day in a range are unable to selected

### ISSUE THREAD

**Issue by zenithC** [patchthecode/JTAppleCalendar#890]
1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.5

2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
yes

3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.
Hi,
I try to select a range of days by this,
`let fromDate = Date(timeIntervalSince1970: 1535385600)` Tuesday, August 28, 2018 12:00:00 AM GMT+08:00 
`let toDate = Date(timeIntervalSince1970: 1536508800)` Monday, September 10, 2018 12:00:00 AM GMT+08:00
`calendarView.selectDates(from: fromDate, to: toDate)`

but some of the days are not selected as shown in the image 
<img width="343" alt="screen shot 2018-09-10 at 5 45 24 pm" src="https://user-images.githubusercontent.com/43134415/45290642-b5e50200-b522-11e8-871a-fdc18ca911ec.png">

Here are the viewController I write for reproducing the problem
https://gist.github.com/zenithC/a07d6b81dcd30b46601c95f7e4d36e15

Thanks

**Comment by zenithC** [comment]
the start Date is the firstDate of current month, i.e. 1 sept 2018, endDate is one year after, i.e. 31 Aug 2019

**Comment by patchthecode** [comment]
> However, is it possible to create a calendar start in current month and able to select the day not in month?

Ok. i see what the problem is now.
Although it cannot be selected programatically, It can be selected manually. 

Hmm. solution can be a this.
Can you create a date boundary? https://github.com/patchthecode/JTAppleCalendar/issues/365

and if added to this date boundary, you also do not want to extra generated month to be visible, then you can just make the `cell.isHidden = true` if the dates belong to a month outside of your boundary.

**Comment by zenithC** [comment]
I see,

Thanks you for your help and advice !
