### ISSUE TITLE
Can change dateLabel color for events but not dateLabel.backgroundColor

### ISSUE THREAD

**Issue by cluelessoodles** [patchthecode/JTAppleCalendar#907]
Using version 7.1.5

I have the monthly calender collection view set up and a xml that I am parsing to get some dates. I am trying to show these dates with round borders on the calendarview but am running into an issue that I'm not sure how to fix - dates that are not from the xml also show up with borders around them and then random change when you scroll to the next month and back, like this - https://imgur.com/a/mxyUtJe

At the bottom of the this post, I also try to just change the label.textColor for the dates found in XML and for reasons I dont understand, that works correctly but the label.backgroundColor does not.

Here is my code for settings borders right now. Is there anything visibly wrong or missing?
```swift
    //Mark: Configure Calendar Cell
    func configureCalendarCell(cell: JTAppleCell?, cellState: CellState) {
        guard let myCustomCell = cell as? CalendarCell else { return }
        
        //configure functions including:
        getEventDates(cell: myCustomCell, cellState: cellState)
    }

    //Mark: set events from XML == selected cell from Calendar
    func getEventDates(cell: CalendarCell, cellState: CellState) {
        
            for calendarDate in tableViewDataSource {
                let datesFromCalendarXML = calendarDate.date
                //print("Found \(datesFromCalendarXML)") This prints dates parsed from XML file - See picture if helpful - https://imgur.com/a/3BAEaOf

                let visibleDatesToString = formatter.string(from: cellState.date)
                //print("Visible dates \(visibleDatesToString)") This prints all of the dates in the current month showing. So for September, it shows all of the dates in September. See picture if helpful - https://imgur.com/a/cedVA3J
                
                // If there is a date match, then show a round blue border
                if datesFromCalendarXML == visibleDatesToString {
      
                    cell.dateLabel.layer.cornerRadius = 25
                    cell.dateLabel.layer.borderWidth = 3
                    cell.dateLabel.layer.borderColor = UIColor.blue.cgColor
                    cell.dateLabel.clipsToBounds = true
                
                // If there is no date match, show no border. I had set this to UIColor.clear.cgColor but then only the last datesFromCalendarXML Oct 30 showed as a blue, so I changed it to red and saw that random dates including the ones from the XML are being circled red.
                } else if datesFromCalendarXML != visibleDatesToString {
                    cell.dateLabel.layer.borderColor = UIColor.red.cgColor
                    cell.dateLabel.clipsToBounds = true
                }
        }
    }
}
```
It seems this only works for the last value in datesFromCalendarXML as Oct 30 shows up with a blue ring. The other values in the XML, Sept 1, 10, 20 and Oct 1, 10, 20 show up with red rings as do other random dates.

.....

I then tried to just change the color of the datelabel instead to green and for whatever reason, that works correctly to make only the matched dates green and does not add random other green dates. I have no idea why I can change the dateLabel.textColor and not the background - https://imgur.com/a/St3b8ND

    if datesFromCalendarXML == visibleDatesToString {
                    cell.dateLabel.textColor = UIColor.green
                    
                } else if datesFromCalendarXML != visibleDatesToString {
                    
                }

Do you know why it works this way?

**Comment by patchthecode** [comment]
This looks like code that is more specific to your project, but not specific to the calendar library. I am trying not to respond to questions like these because i am getting way to many of them and and cannot keep up.

But just you give you a tip, it looks like your code in this function might be wrong
```swift
func getEventDates(cell: CalendarCell, cellState: CellState) { ... }
```

In that function you have a loop.
So imagine this, a **Cell** goes to that function to have its color changed.
It enters the for-loop of that function and then hits this line of code
```swift
if datesFromCalendarXML == visibleDatesToString {
```
So lets say the dates are equal. It will enter that if-statement and run this code right?
```swift
                    cell.dateLabel.layer.cornerRadius = 25
                    cell.dateLabel.layer.borderWidth = 3
                    cell.dateLabel.layer.borderColor = UIColor.blue.cgColor
                    cell.dateLabel.clipsToBounds = true
```

ok great all is well. The cell is configured.
But then there is a problem. You have a **for-loop**
Therefore that **same cell** is again run in the for-loop where it again hits this line of code 
```swift
if datesFromCalendarXML == visibleDatesToString {
```
Now, on this 2nd run of the for-loop, the value is false, therefore it runs this line of code.
```
cell.dateLabel.layer.borderColor = UIColor.red.cgColor
cell.dateLabel.clipsToBounds = true
```
You have now successfully unconfigured the cell you have just configured. And there is your bug.
Now given the length of this explanation, you can see why i am trying not to answer questions which are unrelated to the library.
But i hope you have enough info to fix this now.
Closing this issue :)
