### ISSUE TITLE
selection is not working when I will put calendar inside UITableviewcell

### ISSUE THREAD

**Issue by samulegold2016** [patchthecode/JTAppleCalendar#91]
Hi

I am using JTAppleCalendar control inside UITableviewCell.
Everything is working as well.

But selection is not working as well.

func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {

}

this delegate function is not calling. How can I fix issue?

Thanks.

**Comment by patchthecode** [comment]
So youre saying that:

--> It works correctly outside of the cell but it does **not** work when inside the cell?

If this is the case, then since it is inside of a cell, then maybe the touch events are going to your UITableViewCell and not JTAppleCalendar cells?

Maybe you can investigate and see which view is getting the touch events?

If these hints do not help you, then can you send a zipped copy of a sample project with the bug?

**Comment by patchthecode** [comment]
Is this still an issue? I have not heard a reply in 3 days.

**Comment by patchthecode** [comment]
Since there is no reply in 3 days. I will assume you have resolved this. Please re-open this if it is still a problem, or if you have any more questions.
