### ISSUE TITLE
visibleDates.monthDates giving wrong dates when a week calendar

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#910]
I am using the latest branch.
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

`visibleDates.monthDates` giving wrong dates in week calendar.
<img width="331" alt="wrong-visible-month-dates" src="https://user-images.githubusercontent.com/3313412/46124965-7158a680-c244-11e8-88b1-f48b7ce6769c.png">

So as you can see in the calendar, what should be the output of `visibleDates.monthDates`?

It includes all the dates in above screenshot. Btw, 

`visibleDates.indates` = 0
`visibleDates.outdates` = 0

And congratulations on 5k+ stars. 🥇

**Comment by patchthecode** [comment]
totally missed this.
probably fixed?

not occurring in any tests.
closing this issue.

but if this still a problem for you then lrt me know and i'll re-open this right away.

**Comment by patchthecode** [comment]
but i suspect, it might be an error in your config? (assumption)
because, 2018 september week view with sunday as start of the week should look like this
<img width="334" alt="Screen Shot 2019-03-15 at 7 23 03 AM" src="https://user-images.githubusercontent.com/2439146/54438140-52b37280-46f3-11e9-856f-3b1fa17f9bf0.png">

Instead of the pic above.

**Comment by hemangshah** [comment]
I no longer have access to that project - you can close this for now. Thanks @patchthecode .
