### ISSUE TITLE
Wired problem when reloadData

### ISSUE THREAD

**Issue by loverde-co** [patchthecode/JTAppleCalendar#927]
Version is 7.1.6.
I have follow all youtube videos and the calendar worked fine yesterday.
Today, i dont know if it is Brazilian Summer Time. But, this is happend.
![iphonese_ios_12_funcionando](https://user-images.githubusercontent.com/1157835/47466252-cb5a7680-d7c6-11e8-99e1-d57bd041e71d.gif)
As you can see on this gif, November works well as October ( current month in this conversation ).
When i scroll ( animation false ) to next month ( december ou january 2019 ), loads ok. But when click on any day it go back to October.
If i remove the reloadData, works fine, but i cant get data on black ( server return )
Tested on iOS 12 and 10.3.

**Comment by patchthecode** [comment]
so just to clarify, this is a fresh code base using version 7.1.6?
Or did you recently update from a previous version? I am asking so that  i know if this is a bug that is recently introduced, or something else.

**Comment by loverde-co** [comment]
1 - yep, fresh, no updates.
2 - yes, stars on October and ends 10 years after.
3 - nothing than the videos ( custom layout only )
4 - tried all reloads ( completion, dates in array, only reload ).

**Comment by patchthecode** [comment]
sorry, i didnt respond in time.
Is it possible you can send me a sample zipped project with the issue?
just drag the zipped file in this chat box.

**Comment by loverde-co** [comment]
Hi, give me some minutes to mount an example ( this project has NDA ). ASAP i edit this post with attachment! Thanks!

**Comment by patchthecode** [comment]
thanks. taking a look.

**Comment by patchthecode** [comment]
Ok. I have looked at the sample app.

This happens because the calendarView's width/height change when you do a scroll.
When ever you do any thing to the calendar that affects its width/height, the calendar invalidates its cells because it has to make the cells now fit the new width/height of the calendar so that it has 7 columns and 6 rows visible to the user.  

So when you call **reloadData** when the calendar is in an invalidated state, it rebuilds all its cells and resets to the beginning date. This is expected UICollectionView behavior. There are other actions that will cause the calendar to be reset -> these include the following. It resets because the cell's size or total count will change.

```swift
            if
                // ConfigParameters were changed
                newStartOfMonth                     != oldStartOfMonth ||
                newEndOfMonth                       != oldEndOfMonth ||
                newDateBoundary.calendar            != _cachedConfiguration.calendar ||
                newDateBoundary.numberOfRows        != _cachedConfiguration.numberOfRows ||
                newDateBoundary.generateInDates     != _cachedConfiguration.generateInDates ||
                newDateBoundary.generateOutDates    != _cachedConfiguration.generateOutDates ||
                newDateBoundary.firstDayOfWeek      != _cachedConfiguration.firstDayOfWeek ||
                newDateBoundary.hasStrictBoundaries != _cachedConfiguration.hasStrictBoundaries ||
                // Other layout information were changed
                minimumInteritemSpacing  != calendarLayout.minimumInteritemSpacing ||
                minimumLineSpacing       != calendarLayout.minimumLineSpacing ||
                sectionInset             != calendarLayout.sectionInset ||
                lastMonthSize            != newLastMonth ||
                allowsDateCellStretching != calendarLayout.allowsDateCellStretching ||
                scrollDirection          != calendarLayout.scrollDirection ||
```

Now the real question is why is your calendar frame height changing on scroll?

This was hard to track down. The calendar constraints was the problem. It does not have a fixed height. Currently its constraints are relative to its superview, and when you hit scrollToDate, that relative size changed, which caused the calendar to reset. The fix is simply to give your calendar a fixed height instead of a relative one that is based on its superview.

**Comment by patchthecode** [comment]
Also as a side note, to scroll to the next month, why not use this?
```swift
calendarController.scrollToSegment(.next)
```

**Comment by patchthecode** [comment]
I just notices, that you can even see the size of the cells changing in your gif above. You can see the cell labels top slightly changed when you click.

**Comment by loverde-co** [comment]
Thanks @patchthecode! I did not look at size, I never thought about it, sorry for that! And "Roger that" now rsrsr.
On this `scrollToSegment`, I copied from the video, in Doc I could not find it easier than the video. But it's good to know! I'm going to use it, better than the example I sent you.
Thank you very much again!

**Comment by patchthecode** [comment]
cool.
btw, i saw that you had this -> 
```swift
        calendarController.visibleDates { (visibleDates) in
            ...
            ...
            self.calendarController.reloadData()   
        }
```

Might sometimes be problematic to reload if not on the main thread.
Closing this issue now.
let me know if any other questions.
