### ISSUE TITLE
I need all of your help

### ISSUE THREAD

**Issue by beajco** [patchthecode/JTAppleCalendar#949]
Is there anyone here created a yearly view of a calendar? and when i click the month of that it will open.

Please help me..

**Comment by patchthecode** [comment]
yearly calendar is not possible with this library.
You can create "limited" yearly view, but it is not ideal because it will be laggy when scrolling. This lib was not built to support yearly. I have not seen any one successfully implement it as yet.

This feature has been asked for for some time, but will not be implemented with this lib.
I'm thinking that creating another lib for it will be ideal.

**Comment by patchthecode** [comment]
Let me know if this answered your question.
