### ISSUE TITLE
After reloadItems(at:) and switching the month `didDeselectDate` function isn't getting called

### ISSUE THREAD

**Issue by Nikaaner** [patchthecode/JTAppleCalendar#967]
Hey. It seemed to me that the easiest way to explain the problem is as QA does.

Prerequisites: 
- latest version 7.1.6
- `allowsMultipleSelection = false`
- after `reloadItems(at indexPaths: [IndexPath])` (for example, to add indicators to the cells)
- shows cell highlight in `didSelectDate` func
- hides cell highlight in `didDeselectDate` func
- using `cellState.isSelected` property

Steps:
1. Switch to the previous month (or next) and go back
2. Select some not selected date
3. Switch to the previous month (or next) and go back
4. Select some not selected date in the same month as the previous selected date
5. Switch to the previous month (or next) and go back
6. Select some not selected date in the same month as the previous selected date

Actual Result:
We see several selected dates.

Expected Result:
Only the last selected date should be highlighted.

Sample:
[CalendarBugs.zip](https://github.com/patchthecode/JTAppleCalendar/files/2733720/CalendarBugs.zip)

**Comment by patchthecode** [comment]
looking into this

**Comment by patchthecode** [comment]
Sorry for the late reply. Was caught up between projects.

bug is here.
```swift
    private var events: Set<Date> = [] {
        didSet {
            calendarView.reloadData()
//            calendarView.reloadItems(at: calendarView.indexPathsForVisibleItems)
        }
    }
```

Just comment out the code and it will work fine.
`reloadItems` is a UICollectionView function, not a JTAppleCalendar function.

The fix above can be accomplished using any of the following JTAppleCalendar code.
1. calendarView.reloadData()
2. calendarView.reloadDates([arrayOfDatesToReload])
3. etc etc (once it is a JTAppleCalendar function)

in the next version of this library, i will try to block as many UICollectionView direct functions where necessary so that developers dont get confused.

**Comment by patchthecode** [comment]
Let me know if this helped.

**Comment by Nikaaner** [comment]
Yeah, thank you. Sorry for the late reply too :)
