### ISSUE TITLE
do not generate previous date in current month

### ISSUE THREAD

**Issue by MrShafiee** [patchthecode/JTAppleCalendar#999]
First of all, this is the best Calendar library ever! thanks 👍 
My question is how can I disable generate previous date in current month. I set **generateInDates: .off** and **generateOutDates: .off** to prevent generate indate and outdate for other months.
for example today is 15 Feb and if I use week mode it generate February days from 1 to 28 but I want it show only days from 15 to 28 and user can not be able to scroll days 1 to 15 cells.

Thanks.

**Comment by MrShafiee** [comment]
@patchthecode Do you have any idea about it?

**Comment by patchthecode** [comment]
Hmm. this is one of the features that was asked for since this project began.
But i never got the time to do it unfortunately.

It will generate dates form the start of the month to the end of the month.
To get around this can you use something like data boundaries? -> https://github.com/patchthecode/JTAppleCalendar/issues/365

Basically set boundary on the scroll of a date. Can this work for you?

**Comment by MrShafiee** [comment]
Thanks for your reply @patchthecode, unfortunately it did not solve my problem and I implemented it.
👍

**Comment by patchthecode** [comment]
it is not preventing the user from scrolling back?
needed some more idea as to how it didnt work.

**Comment by MrShafiee** [comment]
No in my case it was simple calendar in week mode, thus I decided to write it completely by myself, I did not use this library for week mode.

**Comment by patchthecode** [comment]
understood.
cool then.
i think i'll close this issue.
